In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/ShineHop/BDA_CJTheMarket/main/tmk_bda_test.csv')
df = df.drop('Unnamed: 0', axis=1)
df

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,prime_yn
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,M,4,N,20230101,NaN
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,M,4,Y,20230101,NaN
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,F,4,N,20230101,NaN
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,F,3,N,20230102,NaN
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,F,3,N,20230101,NaN
...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,M,5,Y,20230103,NaN
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,F,3,Y,20230102,NaN
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,F,3,Y,20230103,NaN
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,M,4,N,20230104,NaN
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,M,3,N,20230103,NaN

In [5]:
df = df.drop('prime_yn', axis=1)
df

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,M,4,N,20230101
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,M,4,Y,20230101
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,F,4,N,20230101
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,F,3,N,20230102
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,F,3,N,20230101
...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,M,5,Y,20230103
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,F,3,Y,20230102
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,F,3,Y,20230103
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,M,4,N,20230104
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,M,3,N,20230103

In [6]:
# 결측값 확인
df.isnull().sum()

scd              0
product_name     0
net_order_qty    0
net_order_amt    0
gender           0
age_grp          0
employee_yn      0
order_date       0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19660 entries, 0 to 19659
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scd            19660 non-null  int64
 1   product_name   19660 non-null  object
 2   net_order_qty  19660 non-null  int64
 3   net_order_amt  19660 non-null  float64
 4   gender         19660 non-null  object
 5   age_grp        19660 non-null  int64
 6   employee_yn    19660 non-null  object
 7   order_date     19660 non-null  int64
dtypes: float64(1), int64(4), object(3)
memory usage: 1.2+ MB

In [9]:
# 프라임 회원 유무 인코딩 (1 = 프라임 회원, 0 = 일반 회원)
#map_prime = {'N':0, 'Y':1}
#df['prime_yn'] = df['prime_yn'].map(map_prime)
#df

In [10]:
# 성별 인코딩 (1 = Male, 0 = Female)
map_gender = {'F':0, 'M':1}
df['gender'] = df['gender'].map(map_gender)
df

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101
...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103

In [11]:
# 구매일자 인코딩
df['weekday'] = df['order_date'].apply(lambda x: pd.to_datetime(str(x), format='%Y-%m-%d'))
df['weekday'] = df['weekday'].dt.weekday
df

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,6
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,6
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,6
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,0
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,6
...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,0
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,2
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1

In [12]:
# 요일로 분류 (0 = 월, 1 = 화, 2 = 수, 3 = 목, 4 = 금, 5 = 토, 6 = 일)
df['weekday'].value_counts()

6    6292
0    4768
1    3047
3    1730
2    1495
4    1249
5    1079
Name: weekday, dtype: int64

In [13]:
# 1월 23일 월, 1월 24일 화 : 설 연휴
df['weekday'] = np.where((df['weekday']==5) | (df['weekday']==6) | (df['order_date']==2023-1-23) | (df['order_date']==2023-1-24), 0, 1)
df

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0
...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1

In [14]:
# 평일 / 주말 및 공휴일로 분류 (1 = 평일, 0 = 주말 및 공휴일)
df['weekday'].value_counts()

1    12289
0     7371
Name: weekday, dtype: int64

In [15]:
# 이벤트 할인 제품 총 구매 횟수 (event_product)
# '['가 포함되어 있는 제품
# 식물성, 냉동, 배송, 유산균, 눈건강, 피부건강, 1BOX는 이벤트에서 제외
df['event_product'] = np.where((df['product_name'].str.contains(r'\[')) & (-df['product_name'].str.contains('식물성|냉동|배송|유산균|눈건강|피부건강|1BOX|쿡킷')), 1, 0)
df

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday,event_product
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0,0
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0,0
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0,0
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1,0
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0,0
...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1,0
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1,0
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1,0
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1,0
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1,0

In [16]:
# 설 연휴 데이터 제거
#df = df[~df['product_name'].str.contains('23설', na=False, case=False)]
#df

- 0 = 국/김치/김/반찬/두부
- 1 = 스팸/닭가슴살/소시지
- 2 = 신선식품
- 3 = 만두/피자/치킨
- 4 = 핫도그/떡볶이/간식
- 5 = 돈까스/함박/구이
- 6 = 밥/죽/면
- 7 = 밀키트
- 8 = 건강식품
- 9 = 음료/생수/시럽
- 10 = 양념/소스/가루/오일
- 11 = 대용량 식자제

In [31]:
# 중복 데이터 삭제
cj = pd.read_csv('https://raw.githubusercontent.com/ShineHop/BDA_CJTheMarket/main/cj_category.csv')
cj = cj.drop('Unnamed: 0', axis=1)
cj = cj.drop_duplicates()
cj.columns = ['category','product_name']
cj

      category                     product_name
0            0    [생산직송]비비고 포기배추김치 5kg+총각김치 2kg
1            0  [생산직송]비비고 포기김치 5kg+열무김치 900gX2개
2            0                 비비고 순살 고등어구이 60g
3            0       비비고 소고기 미역국 500gx18개(1box)
4            0              비비고 소고기 미역국 500gX6개
...        ...                              ...
1722        11                      크레잇 베이컨 1kg
1723        11                           요리당5kg
1724        11                  크레잇 햄야채볶음밥 280g
1725        11                쉐프솔루션 고기팡팡 미트볼1kg
1726        11            크레잇 생활반찬 고추송송 고기말이1kg

[1724 rows x 2 columns]

In [32]:
cj = cj.astype({'category': 'string'})
cj.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1724 entries, 0 to 1726
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   category      1724 non-null   string
 1   product_name  1724 non-null   object
dtypes: object(1), string(1)
memory usage: 40.4+ KB

In [33]:
cj = cj.groupby('product_name').agg({'category': lambda x: ",".join(set(x))})
cj

                                                   category
product_name
(냉동) 비비고 테이블 본갈비탕 700g                                    0
(냉동) 비비고 테이블 본갈비탕 700gX2개 + 특설렁탕 700gX2개 + 특양지곰...        0
(냉동) 비비고 테이블 본갈비탕 700gX3개                                 0
(냉동) 비비고 테이블 특 선물세트 (본갈비탕700g + 특양지곰탕700g + 특설렁...        0
(냉동) 비비고 테이블 특설렁탕 700g                                    0
...                                                     ...
헬씨누리 침향환 환심 10환                                           8
헬씨누리 침향환 환심 10환X6입(1BOX)                                  8
호도과자용가루5 11kg                                            11
훈제대란 20구                                                  0
흑삼정 골드클래스 100gX2개                                         8

[1667 rows x 1 columns]

In [34]:
cj_new = pd.merge(df, cj, on='product_name', how='left')
cj_new

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday,event_product,category
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0,0,0
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0,0,<NA>
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0,0,<NA>
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1,0,0
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1,0,3
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1,0,10
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1,0,4
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1,0,5
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1,0,"3,6"

In [35]:
cj_new.isnull().sum()

scd                 0
product_name        0
net_order_qty       0
net_order_amt       0
gender              0
age_grp             0
employee_yn         0
order_date          0
weekday             0
event_product       0
category         7015
dtype: int64

In [36]:
# 결측치 12로 대체
cj_new = cj_new.fillna('12')

In [37]:
# 배정되지 않은 카테고리
# list_11 첫번째
list_11 = ['15kg', '3.6L', '5kg', '1.4kg', '1.5L', '1.25kg', '3kg', '20kg', '6.5kg', '14kg', '1.45kg', '2.45kg', 
           '11kg', '9kg', '25kg']
# list_10 두번째
list_10 = ['포도씨유', '양념', '올리브유', '쌈장', '소스', '다진마늘', '고추장', '참치액', '가루', '기름', '맛술',
          '드레싱', '시즈닝', '카놀라유', '간장', '올리브유', '다시마', '요리유', '비빔장', '된장', '식초', '다시다',
          '올리고당', '설탕', '액젓', '믹스', '천일염', '참깨', '굴소스', '가루', '옥수수유', '해바라기씨유', '쌀엿']
# list_2 세번째
list_2 = ['오리', '배', '고구마', '망고', '블루베리', '오렌지', '양갈비', '육포', '랍스터', '삼겹살', '목심살', '사과', 
          '토마토', '키위', '매실', '항정살', '한우', '청도', '스위트콘', '대추', '명란젓', '새우튀김', '황도', '양파', 
          '갈비','감자', '한돈', '날개', '닭', '야자', '버섯', '멜론']

list_6 = ['햇반', '죽', '냉면', '짬뽕', '동치미', '메밀', '우동', '잡채', '짜장', '밀면', '파스타', '쌀국수', 
          '야끼소바', '콩국수', '소면', '당면', '죽', '스파게티', '덮밥', '쫄면', '수프', '마라탕', '리조또', 
          '떡볶이떡', '칼국수', '뇨끼', '밸런스밀', '병아리콩']
list_0 = ['김치', '구이', '탕', '미역국', '육개장', '국물', '두부', '찌개', '무국', '국', '김', '유부', '단무지', 
          '메추리알', '쌈무', '볶음', '어묵', '조림', '밥이랑', '육수', '조림', '마늘', '란', '오이지', '장아찌']
list_3 = ['피자', '치킨', '교자', '순살', '너겟', '만두', '탕수육', '봉', '구이', '윙', '칠리새우', '깐풍기', 
          '닭강정', '새우튀김']
list_4 = ['츄러스', '밤', '핫도그', '쁘띠첼', '떡볶이' '바삭칩', '맥스봉', '핫랩', '면볶이', '고메 베이커리', 
          '냉동감자', '팝콘', '찹쌀떡', '스크림', '아몬드']
list_5 = ['스테이크', '카츠', '미트볼', '떡갈비', '동그랑땡', '까스', '불고기', '완자', '너비아니', '고기말이', '바베큐바']
list_1 = ['닭가슴살', '햄', '베이컨', '후랑크', '비엔나', '스팸', '통삼겹', '소시지', '킬바사', '더블에이징', '부어스트', '']
list_8 = ['오메가', '루테인', '유산균', '영양', '전립소', '비타민', '팻다운', '리턴업', '바이오코어', '홍삼', '흑삼',
          '콜라겐', '멀티', '배도라지', '양배추', '한뿌리', '닥터뉴트리', '환심']
list_9 = ['아이시스', '트레비', '삼다수', '콜라', '석류', '토레타', '컨디션', '사이다', '얼티브', 'W차', '파우더', '청', 
          '미초', '커피', '시럽', '식혜', '아이누리', '플리또', '메티에', '보리']
list_7 = ['쿡킷', '밀키트']

In [38]:
list_10 = '|'.join(list_10)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_10)), 'category'] = '10'

In [39]:
list_6 = '|'.join(list_6)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_6)), 'category'] = '6'

In [40]:
list_8 = '|'.join(list_8)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_8)), 'category'] = '8'

In [41]:
list_0 = '|'.join(list_0)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_0)), 'category'] = '0'

In [42]:
list_1 = '|'.join(list_1)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_1)), 'category'] = '1'

In [43]:
list_2 = '|'.join(list_2)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_2)), 'category'] = '2'

In [44]:
list_3 = '|'.join(list_3)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_3)), 'category'] = '3'

In [45]:
list_4 = '|'.join(list_4)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_4)), 'category'] = '4'

In [46]:
list_5 = '|'.join(list_5)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_5)), 'category'] = '5'

In [47]:
list_7 = '|'.join(list_7)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_7)), 'category'] = '7'

In [48]:
list_9 = '|'.join(list_9)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_9)), 'category'] = '9'

In [49]:
list_11 = '|'.join(list_11)
cj_new.loc[(cj_new['category']=='12')&(cj_new['product_name'].str.contains(list_11)), 'category'] = '11'
cj_new

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday,event_product,category
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0,0,0
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0,0,0
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0,0,1
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1,0,0
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1,0,3
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1,0,10
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1,0,4
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1,0,5
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1,0,"3,6"

In [50]:
# 12로 대체했던 결측치가 모두 사라짐
cj_new['category'].value_counts()

6        4378
0        4284
1        3319
3        2341
10       1962
4        1126
5         967
8         515
3,6       323
9         193
11         87
0,4        51
2          37
11,10      29
11,4       23
6,4        10
11,1        7
11,0        5
8,9         2
2,3         1
Name: category, dtype: Int64

In [51]:
# num_category 계산을 위해 추가
cj_new['num_category'] = cj_new['category']

카테고리 축약
- 요리 : 국/김치/김/반찬/두부, 스팸/닭가슴살/소시지, 신선식품 (0, 1, 2)
- 간식 : 만두/피자/치킨, 핫도그/떡볶이/간식, 돈까스/함박/구이 (3, 4, 5)
- 식사 : 밥/죽/면, 밀키트 (6, 7)
- 기타 : 건강식품, 음료/생수/시럽, 양념/소스/가루/오일, 대용량 식자재 (8, 9, 10, 11)

In [52]:
def cate(x):
    if x=='0' or x=='1' or x=='2' : return '0'
    elif x=='3' or x=='4' or x=='5' : return '1'
    elif x=='6' or x=='7' : return '2'
    elif x=='6,3' or x=='6,4' : return '1,2'
    elif x=='0,4' or x=='3,2' : return '0,1'
    elif x=='10,11' or x=='8,9' : return '3'
    elif x=='0,11' or x=='11,1' : return '0,3'
    elif x=='11,4' : return '1,3'
    else : return '3'

In [53]:
cj_new['category'] = cj_new['category'].apply(cate)
cj_new

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday,event_product,category,num_category
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0,0,0,0
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0,0,0,0
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0,0,0,1
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1,0,0,0
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1,0,1,3
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1,0,3,10
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1,0,1,4
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1,0,1,5
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1,0,3,"3,6"

In [54]:
cj_new['amt/qty'] = cj_new['net_order_amt']/cj_new['net_order_qty']
cj_new

,scd,product_name,net_order_qty,net_order_amt,gender,age_grp,employee_yn,order_date,weekday,event_product,category,num_category,amt/qty
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0,0,0,0,8.161946
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0,0,0,0,8.098947
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0,0,0,1,8.277412
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1,0,0,0,3.048458
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0,0,0,0,4.306615
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1,0,1,3,7.930566
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1,0,3,10,8.477412
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1,0,1,4,0.942125
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1,0,1,5,8.594895
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1,0,3,"3,6",8.462103

In [55]:
cj_new = cj_new.rename(columns={'net_order_qty': 'total_qty', 'net_order_amt': 'total_amt'})
cj_new

,scd,product_name,total_qty,total_amt,gender,age_grp,employee_yn,order_date,weekday,event_product,category,num_category,amt/qty
0,20230101964282,비비고 스팸부대찌개 460g,1,8.161946,1,4,N,20230101,0,0,0,0,8.161946
1,20230101970142,삼호 생선살어묵 야채 200g,1,8.098947,1,4,Y,20230101,0,0,0,0,8.098947
2,20230101965237,크레잇 블랙페퍼 폭찹 스테이크,1,8.277412,0,4,N,20230101,0,0,0,1,8.277412
3,20230102973798,비비고 소고기 미역국 500g,3,9.145375,0,3,N,20230102,1,0,0,0,3.048458
4,20230101965633,비비고 소고기 미역국 500g,2,8.613230,0,3,N,20230101,0,0,0,0,4.306615
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,비비고 찐만두168g,1,7.930566,1,5,Y,20230103,1,0,1,3,7.930566
19656,20230102979023,사골곰탕 한 그릇 100g (1-2인분X5개입),1,8.477412,0,3,Y,20230102,1,0,3,10,8.477412
19657,20230103989581,쁘띠첼 자몽상큼함듬뿍워터젤리 130ml,10,9.421249,0,3,Y,20230103,1,0,1,4,0.942125
19658,20230104999357,비비고 언양식 바싹불고기 460g,1,8.594895,1,4,N,20230104,1,0,1,5,8.594895
19659,20230103989710,고메 중화짬뽕 652g,1,8.462103,1,3,N,20230103,1,0,3,"3,6",8.462103

- scd : 주문번호
- gender : 성별 (1 = Male; 0 = Female)
- age_grp : 나이대 (1 = 10대; 2 = 20대; 3 = 30대; 4 = 40대; 5 = 50대; 6 = 60대)
- weekday : 주문일자 (1 = 평일; 0 = 주말 및 공휴일)
- total_qty : 총 주문 수량
- total_amt : 총 주문 금액 (정규화)
- category : 구매한 카테고리 (0 = 요리; 1 = 간식; 2 = 식사; 3 = 기타)
- event_product : 이벤트 할인 제품 총 구매 횟수
- num_category : 구매 제품의 카테고리 개수
- prime_yn : 프라임 회원 유무 (1 = 프라임 회원; 0 = 일반 회원)

In [57]:
cj_new = cj_new[['scd', 'gender', 'age_grp', 'weekday', 'total_qty', 'total_amt', 'category', 'event_product', 'num_category', 'amt/qty', 'employee_yn']]
cj_new

,scd,gender,age_grp,weekday,total_qty,total_amt,category,event_product,num_category,amt/qty,employee_yn
0,20230101964282,1,4,0,1,8.161946,0,0,0,8.161946,N
1,20230101970142,1,4,0,1,8.098947,0,0,0,8.098947,Y
2,20230101965237,0,4,0,1,8.277412,0,0,1,8.277412,N
3,20230102973798,0,3,1,3,9.145375,0,0,0,3.048458,N
4,20230101965633,0,3,0,2,8.613230,0,0,0,4.306615,N
...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,1,5,1,1,7.930566,1,0,3,7.930566,Y
19656,20230102979023,0,3,1,1,8.477412,3,0,10,8.477412,Y
19657,20230103989581,0,3,1,10,9.421249,1,0,4,0.942125,Y
19658,20230104999357,1,4,1,1,8.594895,1,0,5,8.594895,N
19659,20230103989710,1,3,1,1,8.462103,3,0,"3,6",8.462103,N

In [58]:
cj_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19660 entries, 0 to 19659
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scd            19660 non-null  int64
 1   gender         19660 non-null  int64
 2   age_grp        19660 non-null  int64
 3   weekday        19660 non-null  int64
 4   total_qty      19660 non-null  int64
 5   total_amt      19660 non-null  float64
 6   category       19660 non-null  object
 7   event_product  19660 non-null  int64
 8   num_category   19660 non-null  string
 9   amt/qty        19660 non-null  float64
 10  employee_yn    19660 non-null  object
dtypes: float64(2), int64(6), object(2), string(1)
memory usage: 1.8+ MB

In [59]:
cj_new = cj_new.astype({'category': 'string', 'num_category':'string'})

In [60]:
cj_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19660 entries, 0 to 19659
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scd            19660 non-null  int64
 1   gender         19660 non-null  int64
 2   age_grp        19660 non-null  int64
 3   weekday        19660 non-null  int64
 4   total_qty      19660 non-null  int64
 5   total_amt      19660 non-null  float64
 6   category       19660 non-null  string
 7   event_product  19660 non-null  int64
 8   num_category   19660 non-null  string
 9   amt/qty        19660 non-null  float64
 10  employee_yn    19660 non-null  object
dtypes: float64(2), int64(6), object(1), string(2)
memory usage: 1.8+ MB

In [61]:
# category list로 변환
temp=[]
for i in range(len(cj_new)):
    str = cj_new['category'].iloc[i]
    temp.append(str.split(','))
    print(str.split(','))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
['3']
['1']
['3']
['0']
['0']
['3']
['0']
['0']
['0']
['2']
['0']
['0']
['2']
['3']
['1']
['0']
['2']
['0']
['0']
['0']
['2']
['0']
['3']
['3']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['3']
['3']
['0']
['3']
['0']
['0']
['2']
['0']
['3']
['2']
['0']
['0']
['0']
['2']
['0']
['3']
['3']
['0']
['1']
['0']
['3']
['0']
['0']
['0']
['0']
['1']
['1']
['3']
['0']
['2']
['0']
['0']
['2']
['2']
['0']
['2']
['3']
['0']
['0']
['3']
['0']
['2']
['1', '3']
['0']
['3']
['0']
['0']
['3']
['0']
['0', '1']
['0']
['0']
['0']
['0']
['3']
['0']
['2']
['0']
['3']
['0']
['1']
['1']
['3']
['0']
['0']
['3']
['0']
['0']
['3']
['1']
['0']
['2']
['3']
['0']
['3']
['0']
['3']
['0']
['0']
['0']
['0']
['0']
['2']
['1']
['1']
['2']
['0']
['1']
['2']
['2']
['1']
['0']
['2']
['1']
['3']
['1']
['0']
['2']
['2']
['1']
['1']
['1']
['1']
['0']
['1']
['0']
['1']
['2']
['0']
['1']
['1']
['1']
['2']
['0']
['2']
['3']
['1']
['2']
['2']
['1']
['1']
['1']
['1']
['2']
['2']
['2']
['3']
['1']
['0']
['0']
['1']
['1']
['0']
['2']
['1']
['1']
['2']
['0']
['1']
['1']
['3']
['0']
['1']
['1']
['3']
['1']
['1']
['1']
['3']
['1']
['1']
['1']
['1']
['3']
['1']
['0']
['0']
['3']
['2']
['3']
['1']
['2']
['1']
['0']
['1']
['3']
['3']
['2']
['1']
['1']
['2']
['1']
['1']
['2']
['3']
['0']
['1']
['1']
['1']
['3']
['0']
['3']
['2']
['1']
['1']
['2']
['2']
['3']
['0']
['1']
['1']
['2']
['2']
['2']
['2']
['1']
['1']
['2']
['1']
['2']
['3']
['1']
['2']
['2']
['1']
['3']
['1']
['1']
['2']
['1']
['3']
['1']
['1']
['2']
['0']
['1']
['0']
['2']
['2']
['0']
['1']
['0']
['2']
['1']
['1']
['3']
['1']
['3']
['2']
['1']
['1']
['1']
['0']
['0']
['1']
['0']
['0']
['1']
['1']
['2']
['3']
['2']
['1']
['3']
['2']
['0']
['0']
['1']
['1']
['3']
['0']
['3']
['0']
['0']
['0']
['0']
['1']
['0']
['2']
['3']
['1']
['1']
['1']
['1']
['1']
['1']
['0']
['1']
['2']
['1']
['2']
['3']
['2']
['1']
['2']
['1']
['0']
['1']
['1']
['0']
['1']
['1']
['1']
['0']
['3']
['0']
['0']
['1']
['0']
['3']
['0']
['3']
['1']
['0']
['0']
['1']
['3']
['1']
['1']
['0']
['3']
['0']
['1']
['2']
['2']
['3']
['3']
['0']
['0']
['0']
['1']
['0']
['1']
['0']
['0']
['3']
['1']
['0']
['1']
['0']
['1']
['0']
['0']
['0']
['0']
['0']
['2']
['1']
['2']
['0']
['1']
['0']
['1']
['2']
['1']
['1']
['3']
['1']
['1']
['1']
['1']
['0']
['0']
['1']
['1']
['0']
['2']
['0']
['2']
['1']
['1']
['1']
['1']
['0']
['1']
['3']
['1']
['0']
['1']
['2']
['0']
['2']
['0']
['3']
['0']
['2']
['0']
['0']
['1']
['0']
['3']
['3']
['1']
['1']
['1']
['0']
['1']
['3']
['0']
['2']
['1']
['1']
['2']
['1']
['1']
['2']
['1']
['0']
['1']
['1']
['0']
['2']
['0']
['0']
['2']
['2']
['0']
['3']
['1']
['1']
['1']
['3']
['2']
['3']
['0']
['2']
['1']
['3']
['0']
['0']
['2']
['0']
['1']
['0']
['2']
['1']
['1']
['1']
['1']
['2']
['0']
['0']
['0']
['1']
['0']
['1']
['1']
['0']
['0']
['1']
['2']
['0']
['1']
['1']
['2']
['1']
['0']
['1']
['3']
['2']
['0']
['2']
['1']
['0']
['1']
['1']
['1']
['0']
['2']
['2']
['3']
['1']
['1']
['0']
['0']
['3']
['2']
['1']
['0']
['1']
['1']
['1']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['1']
['1']
['0']
['2']
['1']
['0']
['0']
['2']
['2']
['0']
['0']
['0']
['0']
['2']
['1']
['2']
['1']
['2']
['2']
['2']
['0']
['1']
['1']
['1']
['3']
['0']
['1']
['1']
['1']
['0']
['1']
['1']
['1']
['0']
['2']
['0']
['0']
['1']
['1']
['0']
['0']
['0']
['1']
['1']
['1']
['0']
['1']
['0']
['1']
['3']
['2']
['3']
['2']
['2']
['1']
['1']
['1']
['1']
['3']
['2']
['1']
['0']
['1']
['0']
['0']
['1']
['1']
['1']
['3']
['1']
['0']
['1']
['1']
['1']
['3']
['2']
['1']
['2']
['1']
['0']
['2']
['1']
['1']
['1']
['2']
['2']
['1']
['2']
['1']
['2']
['2']
['2']
['2']
['1']
['0']
['0']
['1']
['1']
['2']
['0']
['2']
['1']
['0']
['0']
['1']
['1']
['2']
['2']
['0']
['2']
['1']
['0']
['1']
['1']
['3']
['3']
['1']
['1']
['1']
['1']
['1']
['1']
['1']
['1']
['1']
['0']
['1']
['1']
['2']
['3']
['3']
['2']
['0']
['1']
['1']
['0']
['3']
['1']
['1']
['2']
['1']
['0']
['3']
['0']
['3']
['1']
['1']
['2']
['3']
['0']
['1']
['1']
['1']
['3']
['2']
['1']
['1']
['0']
['2']
['1']
['3']
['2']
['1']
['2']
['2']
['3']
['0']
['0']
['1']
['1']
['1']
['1']
['2']
['2']
['1']
['3']
['3']
['3']
['0']
['1']
['1']
['1']
['3']
['1']
['1']
['0']
['1']
['3']
['1']
['1']
['1']
['0']
['1']
['0']
['2']
['1']
['0']
['1']
['0']
['0']
['1']
['0']
['1']
['1']
['3']
['2']
['2']
['0']
['2']
['1']
['1']
['1']
['3']
['0']
['3']
['1']
['0']
['0']
['3']
['1']
['0']
['1']
['3']
['2']
['0']
['0']
['1']
['0']
['0']
['0']
['2']
['0']
['0']
['2']
['1']
['1']
['3']
['1']
['1']
['1']
['1']
['3']
['1']
['1']
['0']
['1']
['2']
['0']
['1']
['0']
['3']
['1']
['0']
['1']
['0']
['0']
['0']
['0']
['0']
['1']
['1']
['1']
['3']
['2']
['0']
['1']
['3']
['0']
['1']
['1']
['0']
['0']
['2']
['0']
['2']
['1']
['0']
['0']
['1']
['2']
['0']
['2']
['1']
['3']
['1']
['1']
['0']
['0']
['1']
['3']
['1']
['1']
['3']
['0']
['1']
['1']
['0']
['0']
['3']
['2']
['1']
['0']
['0']
['1']
['2']
['0']
['0']
['0']
['0']
['1']
['0']
['0']
['1']
['1']
['0']
['2']
['3']
['0']
['1']
['3']
['2']
['1']
['0']
['1']
['3']
['1']
['0']
['1']
['0']
['1']
['0']
['0']
['1']
['1']
['0']
['1']
['1']
['1']
['1']
['1']
['2']
['0']
['2']
['0']
['0']
['1']
['0']
['1']
['0']
['1']
['3']
['1']
['2']
['1']
['0']
['2']
['3']
['1']
['2']
['1']
['0']
['1']
['1']
['1']
['1']
['0']
['2']
['3']
['0']
['1']
['0']
['3']
['0']
['2']
['0']
['2']
['2']
['2']
['1']
['3']
['1']
['1']
['2']
['0']
['0']
['1']
['0']
['0']
['0']
['0']
['1']
['1']
['0']
['1']
['0']
['0']
['2']
['0']
['2']
['3']
['0']
['0']
['1']
['0']
['1']
['0']
['0']
['1']
['1']
['3']
['1']
['0']
['0']
['0']
['0']
['1']
['3']
['1']
['1']
['0']
['3']
['0']
['1']
['3']
['0']
['0']
['0']
['2']
['0']
['0']
['3']
['1']
['0']
['1']
['3']
['1']
['2']
['0']
['2']
['0']
['3']
['3']
['3']
['1']
['0']
['0']
['1']
['1']
['3']
['2']
['1']
['1']
['1']
['3']
['0']
['1']
['3']
['2']
['0']
['0']
['1']
['3']
['2']
['1']
['1']
['0']
['1']
['3']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['1']
['0']
['1']
['0']
['2']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['0']
['3']
['2']
['1']
['3']
['0']
['0']
['2']
['2']
['1']
['3']
['2']
['3']
['0']
['2']
['0']
['2']
['1']
['3']
['2']
['2']
['0']
['0']
['0']
['2']
['2']
['0']
['0']
['2']
['1']
['3']
['1']
['0']
['1']
['1']
['2']
['1']
['2']
['3']
['2']
['0']
['0']
['1']
['2']
['0']
['0']
['0']
['2']
['3']
['2']
['3']
['3']
['0']
['1']
['1']
['0']
['0']
['3']
['3']
['0']
['0']
['0']
['3']
['2']
['3']
['3']
['0']
['2']
['0']
['1']
['0']
['0']
['0']
['3']
['0']
['3']
['0']
['1']
['3']
['0']
['0']
['0']
['1']
['2']
['2']
['0']
['2']
['0']
['0']
['0']
['1']
['2']
['1']
['3']
['1']
['1']
['0']
['0', '1']
['1']
['1']
['2']
['1']
['3']
['3']
['0']
['0']
['1']
['2']
['1']
['3']
['0']
['0']
['3']
['1']
['1']
['3']
['0']
['2']
['0']
['0']
['0']
['0']
['2']
['2']
['0']
['1']
['1']
['1']
['3']
['1']
['0']
['3']
['0']
['0']
['0']
['1']
['1']
['3']
['1']
['0']
['3']
['0']
['0']
['3']
['0']
['2']
['2']
['2']
['3']
['2']
['2']
['1']
['3']
['0']
['3']
['1']
['1']
['0']
['2']
['2']
['1']
['3']
['0']
['2']
['3']
['3']
['0']
['2']
['1']
['2']
['2']
['0']
['0']
['0']
['0']
['1']
['1', '2']
['1']
['3']
['0']
['3']
['0']
['0']
['1']
['3']
['3']
['0']
['0']
['0']
['1']
['2']
['3']
['0']
['2']
['0']
['3']
['0']
['0']
['0']
['1']
['0']
['1']
['1']
['0']
['3']
['2']
['2']
['0']
['3']
['3']
['2']
['0']
['0']
['0']
['0']
['3']
['3']
['0']
['0']
['1']
['0']
['0']
['1']
['1']
['1']
['2']
['0']
['0']
['3']
['0']
['0']
['1']
['1']
['3']
['3']
['0']
['0']
['1']
['2']
['1']
['2']
['1']
['0']
['2']
['3']
['2']
['2']
['0']
['3']
['2']
['3']
['3']
['1']
['2']
['3']
['1']
['0']
['1']
['1']
['0']
['0']
['3']
['1']
['2']
['3']
['2']
['2']
['2']
['2']
['3']
['0']
['1']
['0']
['0']
['0']
['1']
['0']
['3']
['1']
['3']
['3']
['1']
['2']
['3']
['0']
['2']
['2']
['1']
['0']
['0']
['1']
['0']
['0']
['0', '1']
['1']
['3']
['2']
['1']
['3']
['2']
['2']
['2']
['2']
['1']
['3']
['3']
['1']
['3']
['2']
['2']
['2']
['0']
['3']
['2']
['1', '3']
['2']
['2']
['2']
['1']
['1']
['1', '3']
['1', '3']
['2']
['0']
['2']
['2']
['2']
['0']
['2']
['2']
['1']
['2']
['0']
['0']
['2']
['2']
['3']
['0']
['0']
['1', '3']
['0']
['3']
['0']
['3']
['2']
['0']
['1']
['1']
['1']
['0']
['3']
['2']
['1']
['2']
['0']
['1', '3']
['2']
['2']
['3']
['1']
['1']
['2']
['1']
['0']
['1']
['0']
['2']
['1']
['0']
['3']
['2']
['3']
['3']
['0']
['1', '3']
['2']
['0']
['0']
['2']
['0']
['1']
['1']
['2']
['0']
['2']
['1']
['0', '1']
['0']
['1']
['2']
['1']
['1']
['3']
['1']
['1']
['3']
['1']
['0']
['0']
['0']
['0']
['0']
['2']
['3']
['1']
['0']
['0']
['2']
['3']
['0']
['3']
['0']
['0']
['2']
['0']
['0']
['3']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['2']
['0']
['2']
['0']
['1']
['0']
['2']
['0']
['3']
['2']
['1']
['0']
['0']
['1']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['3']
['0']
['0']
['0']
['1']
['2']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['1']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['2']
['3']
['2']
['0']
['3']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['2']
['0']
['0']
['2']
['3']
['0']
['2']
['0']
['0']
['0']
['3']
['2']
['3']
['2']
['2']
['0']
['0']
['0']
['1']
['0']
['3']
['0']
['0']
['0']
['0']
['2']
['0']
['2']
['3']
['0']
['3']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['3']
['0']
['1']
['0']
['1']
['0']
['0']
['3']
['0']
['0']
['0']
['3']
['0']
['0']
['2']
['1']
['2']
['0']
['0']
['0']
['0']
['0']
['1']
['1']
['1']
['1']
['0']
['3']
['1']
['0']
['2']
['1']
['0']
['1']
['0']
['0']
['1']
['3']
['2']
['3']
['2']
['0']
['0']
['0']
['1']
['0']
['0']
['1']
['0']
['1']
['1']
['1']
['1']
['0']
['1']
['1']
['1']
['1']
['3']
['1']
['3']
['1']
['1']
['1']
['1']
['2']
['2']
['1']
['1']
['0']
['0']
['2']
['1']
['2']
['3']
['1']
['1']
['3']
['1']
['1']
['3']
['1']
['1']
['0']
['1']
['0']
['1']
['1']
['2']
['3']
['3']
['1']
['2']
['1']
['0']
['1']
['0']
['3']
['1']
['1']
['1']
['0']
['2']
['2']
['0']
['1']
['0']
['1']
['0']
['0']
['2']
['1']
['0']
['0']
['0']
['1']
['1']
['1']
['1']
['1']
['2']
['1']
['0']
['3']
['2']
['0']
['0']
['0']
['1']
['1']
['1']
['2']
['3']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['1']
['0']
['3']
['1']
['1']
['0']
['3']
['1']
['0']
['1']
['0']
['0']
['3']
['1']
['3']
['1']
['1']
['3']
['3']
['2']
['3']
['1']
['1']
['2']
['0']
['1']
['0']
['2']
['0']
['2']
['1']
['3']
['1']
['1']
['2']
['1']
['1']
['2']
['0']
['0']
['2']
['2']
['3']
['1']
['1']
['1']
['2']
['1']
['2']
['1']
['0']
['2']
['0']
['0']
['1']
['3']
['1']
['1']
['1']
['1']
['2']
['1']
['0']
['3']
['0']
['1']
['0']
['1']
['1']
['1']
['1']
['1']
['1']
['1']
['3']
['1']
['3']
['1']
['1']
['1']
['1']
['1']
['1']
['0']
['1']
['1']
['0']
['0']
['0']
['1']
['1']
['3']
['3']
['1']
['2']
['1']
['2']
['1']
['3']
['1']
['0']
['1']
['1']
['3']
['2']
['1']
['1']
['3']
['0']
['2']
['1']
['0']
['3']
['0']
['1']
['2']
['0']
['1']
['0']
['0']
['1']
['2']
['2']
['3']
['0']
['1']
['1']
['1']
['0']
['1']
['1']
['2']
['0']
['0']
['2']
['2']
['2']
['3']
['2']
['1']
['1']
['1']
['2']
['1']
['1']
['1']
['0']
['1']
['0']
['1']
['3']
['2']
['2']
['0']
['0']
['2']
['2']
['3']
['2']
['1']
['0']
['3']
['1']
['0']
['3']
['1']
['1']
['0']
['1']
['2']
['1']
['1']
['1']
['1']
['1']
['1']
['0']
['1']
['1']
['2']
['0']
['0']
['1']
['0']
['0']
['2']
['0']
['3']
['0']
['2']
['3']
['1']
['0']
['0']
['0']
['3']
['3']
['1']
['1']
['1']
['1']
['1']
['1']
['1']
['2']
['2']
['2']
['1']
['2']
['0']
['1', '2']
['1']
['1']
['2']
['0']
['2']
['1']
['1']
['1']
['0']
['1']
['0']
['0']
['3']
['2']
['2']
['1']
['1']
['0']
['0']
['3']
['0']
['2']
['2']
['1']
['3']
['0']
['1']
['0']
['0']
['1']
['3']
['0']
['2']
['1']
['1']
['1']
['1']
['1']
['3']
['0']
['2']
['3']
['3']
['3']
['2']
['1']
['1']
['1']
['1']
['2']
['1']
['0']
['1']
['1']
['0']
['2']
['1']
['1']
['3']
['2']
['0']
['0']
['1']
['0']
['1']
['2']
['0']
['3']
['0']
['0']
['1']
['1']
['2']
['2']
['1']
['0']
['3']
['1']
['1']
['1']
['2']
['1']
['1']
['1']
['3']
['0']
['1']
['0']
['1']
['1']
['3']
['1']
['1']
['1']
['2']
['1']
['1']
['1']
['2']
['3']
['1']
['1']
['1']
['1']
['3']
['2']
['1']
['3']
['1']
['1']
['1']
['2']
['1']
['3']
['0']
['0']
['0']
['2']
['1']
['2']
['2']
['0']
['0']
['0']
['1']
['2']
['0']
['1']
['0']
['2']
['1']
['1']
['1']
['2']
['1']
['2']
['1']
['1']
['3']
['3']
['3']
['2']
['0']
['1']
['1']
['2']
['1']
['2']
['3']
['0']
['0']
['1']
['1']
['0']
['1']
['1']
['2']
['1']
['1']
['1', '3']
['1']
['1']
['3']
['0']
['2']
['0']
['0']
['1']
['1']
['1']
['1']
['3']
['2']
['0']
['0']
['2']
['3']
['0']
['3']
['0']
['1']
['1']
['3']
['3']
['0']
['0']
['1']
['0', '1']
['0']
['3']
['3']
['3']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['3']
['0']
['2']
['0']
['0']
['0']
['1']
['1']
['2']
['0']
['1']
['0']
['1']
['0']
['0']
['0']
['2']
['0']
['0']
['2']
['0']
['2']
['2']
['0']
['1']
['3']
['0']
['1']
['2']
['0', '3']
['3']
['0']
['1']
['2']
['0']
['2']
['1']
['0']
['2']
['0']
['0']
['1']
['0']
['2']
['0']
['1']
['0']
['3']
['0']
['0']
['1']
['0']
['2']
['2']
['0']
['0']
['2']
['1']
['0']
['0']
['3']
['2']
['0']
['1']
['0']
['1']
['0']
['3']
['0']
['0']
['1']
['3']
['0']
['0']
['3']
['2']
['3']
['0']
['1']
['1']
['3']
['0']
['0']
['2']
['3']
['1']
['3']
['0']
['0']
['2']
['0']
['0']
['0']
['2']
['0']
['0']
['2']
['1']
['3']
['1']
['1']
['2']
['0']
['0']
['1']
['0']
['2']
['1']
['0']
['0']
['1']
['3']
['0']
['0']
['0']
['3']
['0']
['3']
['1']
['0']
['1']
['0']
['0']
['0']
['0']
['1']
['1']
['3']
['2']
['1']
['1']
['2']
['1']
['1']
['2']
['1']
['2']
['0']
['2']
['1']
['1']
['3']
['2']
['2']
['0']
['1']
['0']
['0']
['0']
['1']
['2']
['1']
['2']
['1']
['1']
['0']
['1']
['2']
['2']
['0']
['0']
['0']
['3']
['0']
['1']
['1']
['3']
['1']
['2']
['1']
['1']
['2']
['0']
['2']
['3']
['2']
['1']
['2']
['1']
['0']
['1']
['2']
['1']
['1']
['1']
['0']
['0']
['2']
['3']
['3']
['2']
['2']
['1']
['1']
['3']
['0']
['3']
['2']
['1']
['1']
['0']
['0']
['2']
['0']
['3']
['0']
['1']
['1']
['1']
['0']
['0']
['2']
['0']
['1']
['0', '3']
['0']
['2']
['0']
['1']
['2']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['2']
['3']
['0']
['0']
['1']
['2']
['0']
['3']
['2']
['3']
['0']
['3']
['0']
['0']
['2']
['1']
['0']
['0']
['2']
['1']
['2']
['2']
['2']
['0']
['0']
['2']
['3']
['3']
['1']
['0']
['0']
['0']
['0']
['1']
['0']
['0']
['0']
['2']
['2']
['0']
['0']
['3']
['2']
['1']
['0']
['3']
['1']
['0']
['1']
['3']
['0']
['2']
['2']
['0']
['2']
['0']
['1']
['0']
['1']
['2']
['2']
['0']
['2']
['0']
['0']
['1']
['3']
['0']
['1']
['3']
['0']
['1']
['3']
['3']
['0']
['0']
['0']
['0']
['2']
['1']
['0']
['0']
['3']
['0']
['1']
['2']
['2']
['3']
['1']
['2']
['1']
['0']
['0']
['0']
['1']
['1']
['0']
['1']
['0']
['1']
['1']
['3']
['3']
['3']
['1']
['0']
['3']
['0']
['2']
['0']
['0']
['0']
['3']
['2']
['3']
['0']
['1']
['0']
['0']
['1']
['1']
['0']
['1']
['2']
['0']
['0']
['0']
['0']
['0']
['3']
['0']
['0']
['0']
['2']
['3']
['0']
['0']
['3']
['0']
['0']
['3']
['0']
['0']
['0']
['1']
['2']
['1']
['0']
['3']
['0']
['0']
['1']
['0']
['1']
['3']
['0']
['0']
['1']
['3']
['1']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['2']
['2']
['2']
['0']
['1']
['0']
['1']
['0']
['3']
['0']
['3']
['0']
['1']
['0']
['0']
['0']
['2']
['1']
['3']
['0']
['3']
['2']
['2']
['3']
['2']
['2']
['1']
['2']
['1']
['2']
['0']
['2']
['1']
['3']
['1']
['2']
['3']
['0']
['3']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['2']
['3']
['0']
['0']
['3']
['0']
['2']
['3']
['2']
['0']
['3']
['0']
['0']
['3']
['2']
['2']
['3']
['3']
['0']
['2']
['3']
['0']
['1']
['1']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['2']
['0']
['1']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['2']
['0']
['1']
['1']
['0']
['0']
['1']
['0']
['0']
['0']
['2']
['1']
['2']
['3']
['2']
['1']
['0']
['3']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['0']
['3']
['0']
['0']
['2']
['0']
['0']
['0']
['1']
['0']
['3']
['2']
['2']
['0']
['0']
['0']
['0']
['0']
['2']
['2']
['3']
['0']
['0']
['0']
['1']
['2']
['0']
['1']
['3']
['2']
['0']
['0']
['0']
['2']
['1']
['0']
['2']
['0']
['3']
['0']
['0']
['0']
['2']
['2']
['2']
['3']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['3']
['1']
['3']
['3']
['0']
['0']
['2']
['0']
['3']
['0']
['0']
['1']
['2']
['2']
['3']
['2']
['2']
['0']
['0']
['3']
['2']
['3']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['3']
['2']
['0']
['0']
['2']
['2']
['0']
['2']
['0']
['1']
['2']
['2']
['2']
['0']
['0']
['3']
['0']
['2']
['0']
['0']
['2']
['1']
['0']
['0']
['0']
['3']
['3']
['2']
['0']
['0']
['0']
['0']
['2']
['3']
['0']
['0']
['0']
['3']
['2']
['1']
['2']
['2']
['0']
['3']
['0']
['2']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['0']
['3']
['2']
['0']
['3']
['2']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['2']
['3']
['2']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['2']
['3']
['0']
['0']
['2']
['0']
['3']
['2']
['2']
['2']
['2']
['3']
['0']
['0']
['1']
['3']
['1']
['0']
['3']
['3']
['2']
['3']
['1']
['3']
['0']
['1']
['1']
['0']
['1']
['2']
['0']
['1']
['1']
['3']
['0']
['3']
['3']
['1']
['0']
['0']
['0']
['0']
['3']
['3']
['0']
['3']
['0']
['0']
['2']
['0']
['2']
['0']
['3']
['0']
['0']
['0']
['2']
['3']
['3']
['3']
['3']
['0']
['0']
['0']
['2']
['1']
['1']
['3']
['0']
['0']
['2']
['2']
['0']
['3']
['3']
['3']
['0']
['0']
['0']
['0']
['0']
['1']
['1']
['2']
['0']
['0']
['0']
['0']
['0']
['0']
['1']
['3']
['0']
['2']
['0']
['3']
['0']
['2']
['1']
['0']
['3']
['0']
['3']
['0']
['0']
['0']
['2']
['3']
['0']
['0']
['3']
['1']
['0']
['2']
['0']
['2']
['1']
['2']
['3']
['0']
['0']
['0']
['2']
['0']
['1']
['1']
['1']
['0']
['2']
['3']
['0']
['0']
['2']
['0']
['2']
['2']
['0']
['2']
['0']
['0']
['3']
['0']
['0']
['3']
['0']
['0']
['1']
['1']
['3']
['0']
['0']
['1']
['0']
['1']
['2']
['0']
['2']
['3']
['3']
['0']
['0']
['1']
['2']
['2']
['0']
['0']
['1']
['1']
['2']
['2']
['1']
['2']
['1']
['1']
['2']
['3']
['3']
['2']
['3']
['3']
['3']
['3']
['1']
['1']
['3']
['2']
['2']
['2']
['1']
['0']
['1']
['3']
['3']
['1']
['0']
['2']
['0']
['2']
['1']
['1']
['2']
['1']
['1']
['0']
['3']
['3']
['3']
['2']
['3']
['0']
['1']
['1']
['0']
['0', '1']
['0']
['0', '1']
['2']
['3']
['2']
['2']
['0']
['3']
['2']
['2']
['2']
['0', '1']
['2']
['2']
['2']
['1']
['1']
['1']
['0', '1']
['0']
['1']
['1']
['3']
['1']
['1']
['1']
['3']
['3']
['1']
['1']
['1']
['2']
['2']
['0']
['3']
['2']
['3']
['1']
['2']
['2']
['2']
['0']
['1']
['1']
['2']
['0']
['1', '3']
['0']
['3']
['1']
['1']
['1']
['1']
['1']
['1']
['1']
['2']
['2']
['2']
['1']
['1']
['3']
['0']
['1']
['2']
['1']
['1']
['2']
['1']
['1']
['3']
['0']
['1']
['1']
['1']
['2']
['1']
['0']
['0']
['1']
['0']
['2']
['2']
['3']
['2']
['0']
['2']
['1']
['1']
['2']
['1']
['3']
['1']
['0']
['1']
['1']
['1']
['1']
['3']
['0']
['1']
['1']
['2']
['1', '3']
['0']
['1']
['3']
['1', '3']
['1']
['0']
['0']
['0']
['2']
['2']
['2']
['2']
['3']
['1']
['2']
['0']
['1']
['2']
['3']
['2']
['3']
['3']
['0']
['1']
['1']
['0']
['0']
['2']
['0']
['3']
['0']
['1']
['2']
['1']
['1']
['1']
['3']
['3']
['0']
['0']
['2']
['0']
['0']
['0']
['3']
['0']
['0']
['2']
['2']
['3']
['3']
['2']
['0']
['1']
['0']
['0']
['3']
['2']
['3']
['2']
['0']
['0']
['0']
['0']
['3']
['1']
['2']
['1']
['1']
['3']
['1']
['0']
['0']
['0']
['0']
['1']
['1']
['1']
['0']
['1']
['2']
['0']
['0']
['0']
['3']
['3']
['0']
['3']
['2']
['0']
['2']
['3']
['0']
['2']
['3']
['3']
['0']
['0']
['0']
['1']
['0']
['0']
['0']
['2']
['1']
['3']
['2']
['1']
['0']
['3']
['0']
['0']
['3']
['0']
['3']
['0']
['0']
['0']
['3']
['0']
['0']
['0']
['1']
['0']
['0']
['0']
['2']
['2']
['1']
['0']
['2']
['3']
['2']
['3']
['1']
['2']
['3']
['0']
['0']
['0']
['2']
['2']
['0']
['0']
['0']
['0']
['2']
['0']
['0']
['0']
['2']
['3']
['0']
['1']
['3']
['0']
['2']
['2']
['1']
['1']
['2']
['2']
['1']
['3']
['0']
['0']
['1']
['3']
['0']
['0']
['0']
['0']
['0']
['3']
['2']
['3']
['0']
['0']
['0']
['0']
['0']
['2']
['0']
['3']
['0']
['1']
['0']
['2']
['2']
['0']
['0']
['0']
['2']
['0']
['2']
['0']
['3']
['0']
['3']
['0']

In [62]:
ctg_temp = pd.DataFrame({
    'ctg' : temp
})
ctg_temp

       ctg
0      [0]
1      [0]
2      [0]
3      [0]
4      [0]
...    ...
19655  [1]
19656  [3]
19657  [1]
19658  [1]
19659  [3]

[19660 rows x 1 columns]

In [63]:
cj_new['category'] = ctg_temp['ctg']
cj_new

,scd,gender,age_grp,weekday,total_qty,total_amt,category,event_product,num_category,amt/qty,employee_yn
0,20230101964282,1,4,0,1,8.161946,[0],0,0,8.161946,N
1,20230101970142,1,4,0,1,8.098947,[0],0,0,8.098947,Y
2,20230101965237,0,4,0,1,8.277412,[0],0,1,8.277412,N
3,20230102973798,0,3,1,3,9.145375,[0],0,0,3.048458,N
4,20230101965633,0,3,0,2,8.613230,[0],0,0,4.306615,N
...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,1,5,1,1,7.930566,[1],0,3,7.930566,Y
19656,20230102979023,0,3,1,1,8.477412,[3],0,10,8.477412,Y
19657,20230103989581,0,3,1,10,9.421249,[1],0,4,0.942125,Y
19658,20230104999357,1,4,1,1,8.594895,[1],0,5,8.594895,N
19659,20230103989710,1,3,1,1,8.462103,[3],0,"3,6",8.462103,N

In [64]:
for i in range(len(cj_new)):
    cj_new['category'].iloc[i] = list(set(cj_new['category'].iloc[i]))

<ipython-input-64-678ec79ae41d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cj_new['category'].iloc[i] = list(set(cj_new['category'].iloc[i]))

In [65]:
cj_new['category'].value_counts()

[0]       7640
[1]       4434
[2]       4378
[3]       3117
[0, 1]      51
[3, 1]      23
[2, 1]      10
[3, 0]       7
Name: category, dtype: int64

In [66]:
cj_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19660 entries, 0 to 19659
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scd            19660 non-null  int64
 1   gender         19660 non-null  int64
 2   age_grp        19660 non-null  int64
 3   weekday        19660 non-null  int64
 4   total_qty      19660 non-null  int64
 5   total_amt      19660 non-null  float64
 6   category       19660 non-null  object
 7   event_product  19660 non-null  int64
 8   num_category   19660 non-null  string
 9   amt/qty        19660 non-null  float64
 10  employee_yn    19660 non-null  object
dtypes: float64(2), int64(6), object(2), string(1)
memory usage: 1.8+ MB

In [67]:
for i in range(len(cj_new)):
    cj_new['category'].iloc[i] = ','.join(s for s in cj_new['category'].iloc[i])

<ipython-input-67-b7a5e79aaeb4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cj_new['category'].iloc[i] = ','.join(s for s in cj_new['category'].iloc[i])

In [68]:
cj_new = cj_new.astype({'category': 'string'})

In [69]:
cj_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19660 entries, 0 to 19659
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scd            19660 non-null  int64
 1   gender         19660 non-null  int64
 2   age_grp        19660 non-null  int64
 3   weekday        19660 non-null  int64
 4   total_qty      19660 non-null  int64
 5   total_amt      19660 non-null  float64
 6   category       19660 non-null  string
 7   event_product  19660 non-null  int64
 8   num_category   19660 non-null  string
 9   amt/qty        19660 non-null  float64
 10  employee_yn    19660 non-null  object
dtypes: float64(2), int64(6), object(1), string(2)
memory usage: 1.8+ MB

In [70]:
cj_new

,scd,gender,age_grp,weekday,total_qty,total_amt,category,event_product,num_category,amt/qty,employee_yn
0,20230101964282,1,4,0,1,8.161946,0,0,0,8.161946,N
1,20230101970142,1,4,0,1,8.098947,0,0,0,8.098947,Y
2,20230101965237,0,4,0,1,8.277412,0,0,1,8.277412,N
3,20230102973798,0,3,1,3,9.145375,0,0,0,3.048458,N
4,20230101965633,0,3,0,2,8.613230,0,0,0,4.306615,N
...,...,...,...,...,...,...,...,...,...,...,...
19655,20230103986821,1,5,1,1,7.930566,1,0,3,7.930566,Y
19656,20230102979023,0,3,1,1,8.477412,3,0,10,8.477412,Y
19657,20230103989581,0,3,1,10,9.421249,1,0,4,0.942125,Y
19658,20230104999357,1,4,1,1,8.594895,1,0,5,8.594895,N
19659,20230103989710,1,3,1,1,8.462103,3,0,"3,6",8.462103,N

In [72]:
# 주문번호 별로 합치기
cj_grp = cj_new.groupby('scd').agg({'gender': pd.Series.mode,
                                   'age_grp': pd.Series.mode,
                                   'weekday': pd.Series.mode,
                                   'total_qty': 'sum',
                                   'total_amt': 'sum',
                                   'category': lambda x: ",".join(set(x)),
                                   'event_product': 'sum',
                                   'num_category': pd.Series.nunique,
                                   'amt/qty': 'mean', 
                                   'employee_yn': pd.Series.mode})
cj_grp

,gender,age_grp,weekday,total_qty,total_amt,category,event_product,num_category,amt/qty,employee_yn
scd,,,,,,,,,,
20230101963221,0,3,0,1,7.959975,1,0,1,7.959975,N
20230101963226,1,3,0,8,37.321156,"2,1",0,2,4.665145,Y
20230101963229,1,5,0,1,9.003808,2,0,1,9.003808,Y
20230101963246,1,2,0,2,9.574080,1,0,1,4.787040,Y
20230101963265,0,3,0,5,43.665790,"2,0,1",0,3,8.733158,Y
...,...,...,...,...,...,...,...,...,...,...
20230131216228,0,3,1,2,9.021961,3,0,1,4.510980,N
20230131216338,1,4,1,3,16.394430,"2,0",0,2,6.092155,N
20230131216371,0,3,1,2,16.019650,"0,1",0,2,8.009825,N
20230131216446,0,4,1,1,8.655214,3,0,1,8.655214,N
20230131216584,1,4,1,1,9.036701,1,0,1,9.036701,N

In [73]:
cj_grp['category'].value_counts()

0                  1687
2                   813
3                   680
1                   536
2,0                 454
0,1                 360
3,0                 311
2,0,1               279
2,3,0,1             252
2,3,0               223
2,1                 194
3,0,1               154
2,3                 117
3,1                 117
2,3,1                93
2,3,0,1,0,1           6
0,1,3,0,1             5
0,1,0                 5
2,0,1,0,1             4
0,1,0,1               3
2,0,1,3,1             3
2,3,2,1,0             2
2,0,1,0               2
2,3,0,1,3,1           2
0,1,3,1               2
3,1,0,3               2
0,1,1                 2
2,0,1,3,0             2
2,0,1,3               2
2,3,1,0               2
2,3,0,3,0,1           1
2,1,0                 1
3,1,3,1               1
2,3,0,3,0,1,3,1       1
2,1,1                 1
2,3,2,1,0,1,3,1       1
2,3,2,1,0,1           1
3,3,1,0               1
3,1,1                 1
2,0,1,1               1
3,0,3,1,0             1
3,1,0,1               1
3,0,0,1               1
2,2,1,0,1             1
Name: category, dtype: Int64

In [74]:
cj_grp['num_category'].value_counts()

1    3351
2    1422
3     774
4     442
5     214
6      91
7      25
8       8
9       1
Name: num_category, dtype: int64

In [75]:
cj_grp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6328 entries, 20230101963221 to 20230131216584
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         6328 non-null   int64
 1   age_grp        6328 non-null   int64
 2   weekday        6328 non-null   int64
 3   total_qty      6328 non-null   int64
 4   total_amt      6328 non-null   float64
 5   category       6328 non-null   string
 6   event_product  6328 non-null   int64
 7   num_category   6328 non-null   int64
 8   amt/qty        6328 non-null   float64
 9   employee_yn    6328 non-null   object
dtypes: float64(2), int64(6), object(1), string(1)
memory usage: 543.8+ KB

In [76]:
for i in range(len(cj_grp)):
    str = cj_grp['category'].iloc[i]
    cj_grp['category'].iloc[i] = ','.join(dict.fromkeys(str))
    print(cj_grp['category'].iloc[i]) # abc

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
3
2
2,,,3,0,1
2,,,1
0
2
2,,,3,0,1
0,,,1
2,,,3,0,1
0
1
2,,,3,0,1
0,,,1
2,,,1
3,,,1
2,,,3,0
3
3,,,0,1
0
1
0
2,,,3,0,1
3,,,0
3
2,,,0,1
3
3,,,0,1
2
1
3,,,0,1
2,,,3,0,1
2,,,0,1
2,,,3
2,,,3,0
0
3
0
2,,,0,1
0,,,1
3
2
0
0
2,,,3,0,1
2,,,1
2,,,3,0,1
2,,,0,1
2,,,0,1
1
2,,,1
0,,,1
1
3
2,,,1
2,,,3,1
2
3,,,0,1
0
3,,,0
1
2,,,3,1
0
0
2,,,3,1
3
3
2,,,0,1
2,,,3,0,1
3,,,1
3,,,1
2,,,0,1
0,,,1
3
0,,,1
2,,,3,0,1
2,,,0
2,,,3,1
2
0,,,1
1
0
2,,,0
3,,,0,1
3,,,0
0
3,,,0
0,,,1
2
2,,,0,1
2,,,0,1
2,,,3,0
2
2,,,1
1
0
3
1
2
3,,,1
2,,,1
2
1
3
2,,,0
0,,,1
2,,,3
1
0
2,,,0
0
0,,,1
0
2
2
3,,,1
3
2,,,3,1
1
3,,,0
2
2,,,3,1
2,,,0,1
3,,,1
1
0,,,1
0,,,1
2
2,,,3,0,1
2,,,3,1
2,,,1
2,,,3,0,1
2,,,3,0
0
3,,,0,1
1
0,,,1
2,,,0
2,,,3,0,1
2,,,1
1
0
2
1
2,,,3,1
2,,,1
2
0
2,,,1
2,,,0,1
3,,,1
3
2,,,3,0,1
2,,,1
2,,,3,0,1
0
0
2,,,3,0,1
0,,,1
2,,,1
1
2,,,0,1
2
2,,,0,1
1
2
2,,,0,1
2,,,0,1
2,,,3,1
0
3,,,0,1
2,,,3,0
3,,,0,1
2,,,3,0,1
1
2,,,3,0,1
0,,,1
2,,,3,0
2,,,0
0
2,,,3,0
1
0
1
2,,,3,0,1
2,,,0,1
2,,,3,1
3,,,1
0
3
2,,,0,1
2,,,1
0
0
2,,,3
1
2,,,0
0
2,,,1
0
1
0
0
2
2,,,1
2,,,0,1
1
1
2,,,0,1
2,,,0
3,,,0,1
1
0
3,,,0,1
3
0,,,1
0
0,,,1
0,,,1
2,,,1
2,,,0,1
0
2
1
2,,,3,0
3
2,,,0
2,,,0,1
3
0
2,,,3,0,1
0
2,,,3
2,,,1
2,,,0,1
2,,,3,0
3
2,,,3,1
0
2
2
0
2,,,1
3,,,0,1
2,,,0
3
2,,,1
0
0,,,1
3,,,0
0
2
2,,,3,0,1
2,,,3,1
2,,,3,0,1
1
2,,,0,1
2
3,,,1
0
0
0
0
0
3,,,1
0
3
2
0,,,1
2,,,0,1
0
2,,,3,0,1
1
2
2,,,0
1
0
0
0,,,1
2,,,3,0
0,,,1
0
2,,,1
0
0,,,1
3,,,1
3
3,,,0,1
0,,,1
1
2,,,0
2,,,0,1
2,,,3
2,,,3
3
2,,,3,0,1
1
0
0,,,1
3,,,1
0,,,1
3
2
2,,,0
2,,,1
3
3,,,0
0,,,1
2,,,1
0,,,1
3
3,,,1
2,,,3,0,1
1
0,,,1
0
0
2
3
3
2
0
1
3,,,0
1
2
0,,,1
1
3
0,,,1
0
2
1
3
2,,,3,1
3,,,0
2,,,0,1
1
0
2,,,3,0,1
1
0
2,,,3,0,1
2
0,,,1
3
3
0,,,1
1
3
2,,,3,0,1
0
2
0
2,,,0,1
3,,,0
2,,,3,0,1
3,,,1
1
0
2
1
2
0
2,,,0,1
1
2,,,0
0
0
2,,,3,0,1
1
2,,,3,0
2,,,3,0,1
3
1
2
0
2,,,3,1
3
3
0
0,,,1
2,,,0,1
0,,,1
3
0
0,,,1
3
0,,,1
0
1
3,,,1
0
1
2,,,0,1
3
3
3
0
0
0
2,,,3,0
3
0
2,,,3,0,1
1
2,,,0,1
2,,,3,1
2,,,1
3,,,0,1
3,,,0
1
2,,,0,1
2,,,0
3,,,0,1
0
3
3,,,0
2
3,,,0
2,,,0,1
1
3
3,,,0,1
3
0
3,,,0,1
2
0
0
2,,,1
0
1
3
2,,,0
1
2,,,1
1
3,,,0
3
3,,,0,1
3,,,1
2
2
1
0
0,,,1
2,,,3,0,1
3
2,,,3,1
3,,,0
2
2,,,0
1
0
0,,,1
1
0
2
3
3
2
2,,,3,0,1
0,,,1
3
2
1
0
0
2
3
3,,,0,1
3,,,1
2,,,0
0,,,1
0
1
0,,,1
0
1
0
3,,,0
2,,,1
2,,,1
0
3
2,,,0,1
2,,,0,1
2,,,0,1
3
1
2,,,0
2,,,3,0
0
3,,,0
2,,,1
2,,,3,0
3,,,0,1
0
1
2,,,3,0,1
0
0
0
2,,,3,1
2,,,0
0
0
0
2,,,0
3
0
3,,,0,1
0
2,,,0,1
2,,,0,1
3,,,0,1
2,,,3,0
2,,,0,1
3,,,0,1
1
2
2,,,0
1
3,,,0,1
2,,,0,1
3,,,0
2,,,0,1
0,,,1
2,,,1
2,,,3
0
3,,,1
2,,,0,1
0,,,1
3,,,0,1
2,,,3,0
0
3,,,0,1
2,,,3,1
3,,,1
1
3,,,0
3
2
2,,,3,1
3,,,0,1
2,,,1
1
3,,,1
2,,,3,1
2
2,,,3,0,1
2,,,3,1
3,,,0,1
3
1
2,,,3,0,1
2,,,0
0
3,,,0
0,,,1
3,,,0
0,,,1
3,,,0,1
3
0
0
2
1
0
1
1
2,,,3,0,1
0
3,,,1
3
3
3,,,1
0
2,,,1
0,,,1
3
3,,,1
2
3
0
2,,,3,1
1
2,,,3,1
3,,,1
0
2,,,3,1
2
1
3
1
1
0
2
2,,,1
0
2
0
2,,,1
2,,,3,1
3
0
2,,,0,1
0
2,,,3,0,1
1
0
1
2
0,,,1
3,,,1
2,,,0,1
0
1
0,,,1
2,,,0
1
0
0
0,,,1
2,,,0,1
0
3
0
2
2
0
0
0
1
3,,,1
2
3
2,,,0
3,,,0,1
3
2,,,3,0,1
2,,,3
2,,,0,1
2,,,3,0,1
0
1
0
0
3,,,0,1
1
2,,,3,0,1
2,,,3,0,1
0
1
2
1
2,,,0,1,3
2,,,0,1
3,,,0
1
3,,,0,1
1
0
0
3,,,0,1
1
2,,,3,0
2,,,1
0,,,1
0
1
1
2,,,0,1
0
0,,,1
0
3
2,,,0,1
0
0
2,,,0
2
2,,,0
3
2,,,1
2
0
0
0
2,,,3,1
3
3
0
0
2
3,,,0,1
3,,,0
0,,,1
0
0
3,,,0
3,,,0
2,,,0
0
2,,,1
3,,,0
2,,,3
0
2,,,3,0
2,,,3,1
1
2,,,1
2,,,0
0
0,,,1
0
3
2
0
0
0
3,,,0,1
2,,,3
3,,,1
0
3
0
1
2
3
0
2,,,3,0
2,,,0,1
3
3
0
1
1
0
3,,,1
2,,,0,1
2,,,0
2,,,3,0,1
2
3,,,1
1
0
2,,,3,1
2,,,3,1
1
0
2
0
3,,,0,1
2,,,0,1
3,,,1
3
3,,,1,0
2,,,1
2,,,1
0
3
2,,,3,1
0,,,1
1
0
2,,,0
2,,,0,1
2,,,3,1
0
3,,,0
3,,,0
0
0
1
0
1
2,,,1
3
0
3,,,0
0
3,,,0
0
0
0
0
0
3,,,0,1
3,,,0,1
2,,,1
2
0
0
1
2
0
2,,,3,0,1
0
2,,,3
0,,,1
3,,,0,1
3,,,1
0
2,,,1
2,,,1
1
2,,,3
1
0,,,1
3
0
1
0
2
2,,,3,0,1
0
0
3,,,0
2,,,3
3,,,1
2,,,0,1
2,,,0,1
0
3,,,1
3
2,,,3,0,1
2,,,3,1
2,,,3,0
2,,,1
0
2
3
2,,,0
0
0,,,1
2,,,3,0,1
0,,,1
0,,,1
3
2,,,3,1
2,,,3,0
0
0
2
2
0
2,,,3,0,1
0,,,1
0
2,,,3,0,1
3,,,0
0
3
2,,,3,0,1
0
0
0
2
1
2,,,3,0,1
1
0
2,,,3,1
2,,,3,0,1
2
2
2,,,3,0,1
2
0
2,,,3,0,1
0,,,1
2
2,,,0,1
2
0
2
3,,,0,1
0
2,,,3
0,,,1
3,,,0
3
2,,,0
3
0
0
3,,,1
3
0
0,,,1
0
3
3,,,1
3
1
2,,,3,0,1
2
0
0
0,,,1
0,,,1
2,,,0
3
3
0
1
0,,,1
3
2
2
2,,,3,1
3
3
0,,,1
0,,,1
2
2,,,0
3,,,0
2
0
1
0
0,,,1
2,,,3,0,1
2,,,3,0
3,,,1
3
3,,,0
3
0,,,1
3
2
0
2,,,0
2,,,3,0
2,,,3,0,1
2,,,0,1
2,,,0
2,,,3,1
0
0,,,1
1
2
2,,,3,0,1
0
2,,,3,0
3,,,1
0
1
3
2,,,3,1
0,,,1
3
3
2,,,1
2
3,,,0
2,,,0,1
0
0
0
2,,,0
2,,,1
3,,,0,1
0
2
2
3
2,,,0
2,,,3,1
3
2
3,,,0
3,,,0,1
3,,,0
3
3
2,,,0
2
3,,,0
2
0
0
0
2,,,0,1
0
0
0
2,,,0
0,,,1
1
0
0
2,,,1
0
3
0
3
1
2,,,3,0
2
0
2
3,,,0
2
0,,,1
2,,,3,0
2,,,3,0,1
3,,,0,1
0
2
0
0,,,1
2,,,0
2
0
3
0
3,,,0,1
0
3,,,0
2,,,3,1
0
0
0
0
1
3,,,0,1
0,,,1
2
2
3
0,,,1
2,,,3,0
3
2,,,0
2
0
0,,,1
2,,,3,1
2,,,0,1
0
2,,,3,0,1
3,,,0
0
1
2,,,0
2,,,3,0,1
1
0
0
2
1
0
0
2
3
2
1
2
0
2,,,0,1
3
2,,,3,0
2
2,,,3,0,1
0
2
3,,,0
0
0
2,,,0
0,,,1
3
2,,,1
3
3,,,0
0
2,,,3,0,1
0
2,,,3,0
1
3
0
0,,,1
2,,,1
0,,,1
1
2
2,,,3
3
1
0
1
3,,,0
0
3,,,0,1
3,,,0
1
1
2,,,3,0,1
2
2,,,1
2
3
3
2,,,0
2,,,3
3,,,0
1
3
0
3
3,,,0
2,,,3
1
3
0
0
1
2,,,0,1
2,,,3,0
0
0
2,,,0,1
0
0,,,1
3
1
3,,,0
3
2
2,,,0,1
2,,,1
1
2,,,1
2,,,3
0
1
2,,,3
2
2,,,3,0
2,,,3,0,1
3,,,0,1
2
2,,,0,1
3
3,,,0
3
1
3,,,0,1
3
0
0
2,,,3,0
2
0,,,1
0
2
0,,,1
0
0
0,,,1
3
2,,,3,0,1
2
3,,,1
0
1
0
2,,,3,1
0
2
1
1
0
2,,,3,0,1
0
1
0,,,1,3
2,,,3,0
3
1
2,,,1
3,,,1
1
3
3,,,0
0
0,,,1
0
2
2,,,1
2
3
0
3,,,1
2,,,0
0,,,1
0
3,,,0
0
0
3,,,0,1
3
2,,,3,1
0
3
0
3
0
3,,,0
0
1
1
2,,,3
0,,,1
2,,,3,1
3,,,0
1
2,,,3,0,1
2,,,3,0,1
0
2,,,3,1
2,,,1
3,,,1
3
2,,,0
3
2
1
0
3,,,0,1
3
2,,,0
0
2,,,0,1
2,,,3,0,1
0
3
3,,,0
3
0
2
0
2,,,0,1
2,,,1
3,,,0
0
2,,,0
3,,,0,1
0
0
0
3
2,,,0,1
0
3,,,0
0,,,1
2,,,1
2,,,3,0,1
2,,,0,1
3
2,,,1
0
3
2,,,3,0,1
0
3,,,0
3
1
0
3
2,,,0,1
2,,,1
0
2,,,0
2,,,1
2,,,3
0
1
3,,,0
0,,,1
0
2,,,0
3,,,0,1
3
1
2,,,0,1
0,,,1
0,,,1
2
2,,,3,0
2
2
0
3,,,0
0
0
3,,,0
2,,,1
3
0
2,,,3,0,1
2
2,,,3,0,1
2
0
0
0
2
3,,,0,1
2,,,1
2,,,3,1
2,,,0,1
0
2
3
0
0,,,1
2,,,0,1
2
3
0
0
3
3,,,0,1
2,,,0,1
1
3
2
1
0
2
2,,,3
2,,,3
2
3
2
0
2,,,0,1
1
3,,,0,1
3
0
3,,,0
2,,,1
3
2,,,0
2
1
0
1
3,,,0,1
0
0
2
2,,,3,1
0
2
2,,,0,1
1
2
0
3,,,1
2,,,3
0
2,,,0,1
0
1
0
2,,,0,1
2,,,0,1
2,,,0
0,,,1
0
2
0
1
2,,,3,0,1
0
2,,,0,1
3
0,,,1
1
1
0
2,,,3
3
2,,,3,0,1
2,,,0,1
0
0
2,,,0
2,,,0,1
0
2,,,0
0
0
2,,,3
3
2,,,0,1
0
2
2
3,,,0,1
3
2,,,3,0,1
3
3,,,0
0
3
0,,,1
0
1
1
2,,,0
0
2,,,3,1
0
0
3
0,,,1
0
0
2,,,3,0
0,,,1
0
2,,,0,1
0
0
3
0
0
2
2
3,,,0
3
2
3,,,1
2,,,3,1
0
2,,,0,1
0
3
0,,,1
2,,,0,1
0
0,,,1
1
2
3
2
0
3
2,,,3
0,,,1
2,,,0,1
3,,,0
3
2
0
3
3
0
2,,,1
0,,,1
3,,,0
3,,,0
0
2
2
1
0,,,1
2
3
2,,,3
3
0
1
0
0
2,,,0,1
0
0
0
0
0,,,1
3
3
0
0
2
0,,,1
0
3
3
0
2,,,3,0,1
0,,,1
3,,,0,1
0
0
3
3
2
3
2
0
3
0,,,1,3
1
0
2
3,,,0
2
2
0
0
3
2,,,1
3,,,0,1
2,,,0,1
2,,,1
3
0
0,,,1
0
0
0
2,,,3,1
1
2,,,0
0
2
0,,,1
2
2,,,0,1
3
2,,,3,0,1
0
0
2,,,0,1
2
2
2,,,1
0,,,1
2,,,0
2,,,3,1
2
1
0
2,,,3,0
0,,,1
2
2,,,0
2
0,,,1
3
3
2,,,3,0
0
3,,,0
0
2,,,1
3
0
2,,,1
0,,,1
2,,,3,1
2,,,0,1
0
3
0
1
2,,,3,0
2
0
3
0
2
0
0
2,,,0
0
0
0
0
3
0
2
2,,,0,1
3,,,0
0
3
2,,,0,1
0
0
0
0
2,,,0
2
2
2,,,1
0
3
3
2
0
2
2
0,,,1
2,,,0
2
2
3
3,,,1
0
0
3
1
0
0,,,1
0
2,,,3,1
0
0
3,,,0
0
2,,,3
0
3
0
1
0
2
2
2,,,0
0
2
2,,,3,1
3
2
2,,,3,0,1
3,,,1
3
1
0
2
2
0
0
2
0
0
2,,,0
3
3,,,0
1
1
3,,,0
3
1
0
2,,,1
2,,,3,0
0
3,,,1
2,,,0,1
3
2,,,3
0
0
1
0
2,,,3
0
0
0
0
0
3
1
1
2
0
3
0
0
0
0
0
3
2,,,0,1
3
0,,,1
3,,,0
2
1
3,,,0
0
3
3,,,0
3
0
2
2
3
3,,,0,1
2
3,,,0
0
3
0
3
0
3
1
0
2
0
3
3
0
3,,,1
2,,,0
3,,,0
0
1
0
0
3
0
3
2,,,0
3
3
2,,,1
3
0
3,,,0
0
3,,,0
2
2,,,0
0
3,,,0
0
0
2,,,0
3,,,0
0
2,,,3,0,1
2,,,3,0
3
1
0,,,1
2,,,1
0
3
0
3
0
0
0
0
0
0
3
0
2
2
3
2,,,1
2,,,3,0,1
3
1
0
0
0,,,1
0
3,,,0,1
3
3
3
2
0
0
3
1
0
0
3
2,,,1
0
2
0
0
3
0
0
0
3
1
0
0
3
3
0
2,,,0
3,,,0
0
0
1
1
0
0,,,1
2,,,3,0
0,,,1
2,,,3,0
1
1
3,,,0
2,,,0,1
3,,,0
0
2
3,,,0
0
1
3,,,0
3
3
0
2,,,1
3
3
3,,,0
2,,,1
0
3
2
0
2
1
3
0
2
2,,,0
0
2,,,1
0
2
2
2
2
2,,,1
2
2
1
2,,,3
2
2,,,0,1
3
3,,,0
3,,,1
2
2,,,0,1
3
2
0
3
0
2,,,1
0
2
2,,,0
0
0
2,,,0
2
2
2,,,3
3
0
0
3
0
0
0
0
0,,,1
2,,,3,0,1
2
3
2,,,0,1
0,,,1
3,,,0
0
0
1
0
0
3
2,,,3
0
1
0,,,1,3
3
1
2,,,0,1
1
3
3,,,0,1
2
1
3,,,0
2
0
0
0
0
1
2,,,3
2
2
3
0
3
3
3
2
0
3,,,1
3,,,1
0
2,,,0,1
0,,,1
3,,,0
0
0
0
3,,,0,1
3
3
0
0
2,,,3,0,1
3
0
0
0
0
2,,,3,0,1
2,,,0
0,,,1
3
0,,,1
0
3,,,0
0
3
3,,,0
2
3,,,0,1
2,,,3,0,1
0
0
0
3
0
0
3
2
3,,,1
0
2,,,0
0
0
3
0
0
3,,,0
0
2,,,3,0,1
0
2,,,0
0
0
2
0
0
2,,,3,0,1
2,,,3,0,1
0
2,,,3
0
3,,,0
0
3
0,,,1
2,,,3,0
2,,,3,0,1
0
0
3
2,,,3,0
0
2,,,0
2,,,0,1
2
3,,,0,1
3
0
0
2,,,0
0
2,,,3,0,1
2,,,3,0,1
2,,,3,0,1
2,,,0
2,,,3,0
0
0
0
3,,,0
3,,,0,1
3
3
2,,,3,0
0
2
0
3
0
0
0
3
3
0
0
3
0
0
0
0
0
3
3
3
0
3
0
0
0
0
0
0
0
0
3
2,,,0
3,,,0
2,,,3,0,1
0
0
0
3
0
0
3
2,,,0
0
2
0
0
0
0
3
0
0
3
0,,,1
0,,,1
0
0
3,,,0,1
1
2,,,3,0,1
1
3
3
0
3
1
0
2,,,3,0
0,,,1
2,,,3,0
0
0
0
0
3
0
2,,,3,0,1
3
0
3
0
2,,,1
0,,,1
3,,,0,1
0
0
0
0
3
3
0
1
0
0
2,,,0
0
2,,,0,1
2,,,3,0,1
2
0
0
1
2,,,3,0
2,,,3,0
1
3
3,,,0
3
0
0
1
2
2,,,3
2,,,0
2,,,3,0,1
0
3
0,,,1
2,,,0,1
3
0
0
0
2,,,3,0,1
1
2,,,0
2,,,3,0
0,,,1
2,,,0,1
2,,,0,1
0
0
3
2
2
3,,,0,1
0
3,,,0
0
0
0
2
2,,,0
2,,,0,1
1
0
2,,,3,0
2
0
0
3
0
0
1
1
0
2,,,3,0,1
0
0
1
0
1
1
1
1
0
0
2,,,1
0
2,,,3,0,1
0
3
0
3
2,,,1
0
2,,,3,0,1
3,,,0,1
3
2,,,3,0
0,,,1
0
0
0
0
2,,,1
2,,,3,0
1
1
2,,,3,0,1
3
0
3
2
3,,,0
1
2,,,0,1
0
0
0
0
0
0
2
3
1
2,,,3,0,1
3
0
0
2
0
3
3
3
3,,,0
3
3
3
0
2,,,3,0
3
2,,,3,0,1
2,,,1
0
0,,,1
0
0,,,1
3,,,1
3
2
0
2,,,0,1
1
0
2,,,0,1
0
0
0
1
0
0
0
0
2
1
3
2,,,0
0
3
0
0
3,,,0
0
3
2,,,0
1
2,,,3,0
0
2,,,1
0
0
2
1
0
0
2,,,1
3
2
3
0
0
0
3
0
0
2
0
3
3
0
0
0
3
0
2
0
2,,,0
3
0
0
3
3
2,,,3,0
0
0
2
3
2
2,,,3
0
0
3
3
0
3
2
0
2
0
3
3,,,1
2,,,0,1,3
0
0
2
3
3
3
3
2,,,0
3
3
0
3
3
3,,,0
2,,,0,1
3,,,0
0
0
3
2
0
2
0
0
0
2
2
2
2
0
2,,,0,1
0
0
0
2
3
3
3
0
0
0
3
3
0
2,,,0
3
0
3
0
0
0
0
0
0
0
3
0
2
0
3
3
2
0
0
3
0
3,,,1
3
2,,,3,0
0
0
0
2
2,,,0
0
0
0,,,1
0
2
0
2,,,3,0,1
0
3
3
0
0
3
3
3,,,0
1
0
3,,,0
0
3
2,,,3,0
3,,,0
2
2,,,0
2,,,3
0,,,1
2,,,3,0,1
2,,,3,0,1
2
2,,,3,1,0
0
2
3
2,,,3
0
0
0
0
0
0
2,,,3,0,1
0
0
2
2,,,3,0,1
2
2,,,3,0
3
0
0
0,,,1
0
3,,,0
2,,,3,0
2,,,3,0,1
2,,,0,1
2,,,0,1
3,,,1
2,,,0,1
3
2,,,3
2,,,3,0
0
0
3
3,,,1,0
2,,,3,0
2,,,3,0,1
0
0
3,,,0
0
1
2
2
3
3
0
0
2,,,3,0,1
1
0
3
2
0
2,,,0,1
0
0
0
0
0
0
0
3
2,,,3,0,1
0
0
2,,,3,0,1
2,,,0
0
3
3
3,,,1
0
0
0,,,1
0
3,,,0
3,,,0
0,,,1
0
2
2,,,0,1
3,,,0
1
0
2,,,3,0,1
1
2,,,0,1
2,,,0,1
0
3
3
1
2,,,3,0,1
2,,,0
0
2,,,3
2,,,3,1
3
2,,,1
0
3
2
0
1
2,,,0,1
3
2,,,3
2,,,0,1
2
2,,,3,0,1
3
0,,,1
0,,,1
2
0
0
2,,,0
2,,,0,1
2,,,0,1
3
0
3
0
0,,,1
0
0
0
3,,,0,1
2,,,0
0
2
3
3
2,,,0,1
0
0
0
3
0
1
3,,,1
2,,,3,0
3,,,0
2,,,3,0,1
0
3
3
2,,,0,1
2,,,0,1
1
2
0,,,1
0,,,1
2
0,,,1
2
0
1
0,,,1
0
2
0,,,1
0
0
1
2,,,0
2
2,,,0,1
1
0
0
2
0
2,,,3,0,1
3,,,0,1
2
0,,,1
0
1
0
0,,,1
0
2,,,0
2,,,0,1
2
0
2
0,,,1
2
3
1
2,,,3,0,1
2,,,3
3
3
2,,,0
0
2
2,,,0,1
3,,,0
2,,,0
1
0
0
0,,,1
2,,,3
2,,,0,1
0,,,1
2
3
0,,,1
2
2
2,,,0
2
0
2,,,0
0
2,,,0,1
3
3,,,0
0
3,,,0
3,,,0,1
2,,,3,0,1
0
3,,,0
2,,,3,0,1
0
2
3,,,0
2
2,,,0,1
0
0
3
3
1
3,,,0
2,,,3,0
3
2,,,0
1
2
2,,,0
3
0
1
3,,,0
2
2,,,0
2
2,,,0
2,,,0
0
2,,,3,0
0
0
2
2
0
1
2,,,0,1
2
0
2,,,0,1
1
3
2,,,3,0,1
3
0,,,1
2,,,0,1
3,,,0,1
0
0
3
0
2,,,3,0,1
3
2,,,3,0
2
2
2
0
2,,,0,1
0
1
0
3
0
3
1
1
3
2,,,1
3,,,0
2,,,0
2
0
3,,,0,1
0,,,1
2
2,,,3,0,1
1
0
2,,,3,0
3
0
3
3
3
0
2
0,,,1
0,,,1
1
2,,,3
2,,,0
2,,,3,0
1
0
3
0
0
2
2,,,3,0
3,,,0
2,,,0
0,,,1
2
2
2,,,0
0
2
0
2
2
0
2
0
0,,,1
0
3
2,,,1
2
0,,,1
2
0
0,,,1
3
2,,,3,0
2
2,,,0,1
3,,,0,1
2,,,0
2,,,3
3
2
0,,,1
0
2
0
0
2,,,0
2,,,0
3,,,0
2,,,0,1
2,,,0
0
2,,,0
2,,,0
2,,,0,1
2
2
2,,,0
2
2,,,0
0
2,,,0
2,,,0
0
3
2,,,3,0
2
0,,,1
0
1
0
0
2
2
2,,,3,0
0
2
2,,,3,0,1
0,,,1
2,,,0
0
2,,,0
0,,,1
0
2,,,3,0
0
2,,,3,0,1
0,,,1
2
0
1
2,,,0
2,,,3
1
1
0
0
2
0,,,1
2,,,3,0
2
0,,,1
0
2,,,0,1
3
2,,,3
1
0
2,,,3
3,,,0
0
1
0
0,,,1
3,,,0
2,,,3,0,1
3
2,,,0,1
1
3
2
2,,,0,1
2,,,0,1
3,,,0,1
2
0
1
3
2,,,0,1
2,,,0,1
2,,,3,0,1
3,,,0,1
2,,,3
2,,,0
2,,,1
2,,,3,1
2,,,0
2,,,0,1
2,,,3,0,1
1
2,,,3,0
2
0
2,,,1
2,,,0
2,,,0,1
3
2,,,3,0
0
1
2,,,3,0
2,,,3,0,1
2,,,3,0
1
0,,,1
2,,,0
0
2,,,0,1
1
3
2,,,3,1
2
2,,,0
0
0
1
2,,,0
2
2,,,0
2,,,1
0,,,1
2,,,0
2
2
1
0
2,,,1
2,,,3,0
3
1
1
2,,,0,1
2
2,,,3,0,1
0,,,1
0
0
0
2
3
2,,,0,1
2,,,1
2,,,3,0
2
2,,,3,0
2,,,3,0,1
2,,,3
2
2
0
2,,,3,0
0,,,1
2,,,1
0,,,1
2,,,3
2,,,3,0,1
2,,,0
3
3
3
3
2,,,3
0,,,1
0,,,1
0
0
3
0
2
2
3
2
0,,,1
0
2,,,1
3,,,0
0,,,1
0,,,1
2
2,,,3
2
0
0
0,,,1
2
2,,,0
0
0
2,,,3,0,1
0
2,,,3,0
2
0
2
3
0
0,,,1
2
0
2
2
2,,,1
1
0
2
2
2,,,0
0
2
2,,,3,0,1
0
3
2
0,,,1
2
2
2,,,3
2
1
2
0,,,1
1
2,,,0
2,,,1
0
0
3
1
1
2,,,1
1
2,,,0,1
1
2,,,1
2,,,3
3
1
3,,,0,1
0
1
2,,,3
0
2
2
2
3
0,,,1
3
0
0
2,,,1
2,,,3,0,1
2,,,3
2,,,0
3,,,0
0,,,1
2,,,3,0,1
0,,,1
0
2,,,0
2
0,,,1
0,,,1
2,,,0,1
2
3
0
0,,,1
3,,,0
2,,,3,0,1
2,,,0,1
2,,,0
3,,,0,1
1
0
2,,,3,0,1
3
2,,,3
2,,,0
3
2,,,3,0
0
0,,,1
0,,,1
3
3,,,0,1
0,,,1
0
0
2
3
2
2,,,0
3,,,0
2
2
2,,,0,1
2,,,0
2
2,,,0
2
2,,,3,0,1
2,,,0,1
2,,,3,0
2
2
2,,,3,0
0,,,1
2,,,0
2,,,1
3,,,0,1
3,,,0
0
0
0
0
2,,,3,0,1
2,,,3
0,,,1
2
2,,,0
2,,,3,0
1
3
2,,,3,0
0
2,,,3,0
2,,,0
1
0
3,,,0
0,,,1
2,,,0
2,,,3,0
0
2
2
3,,,0
2
0
3
2,,,0
2,,,0,1
2
3,,,0,1
2,,,0,1
3
2
2,,,3,0
0
3
0
3
2
0
2
3
0,,,1
0,,,1
2,,,3
2
1
2
2,,,0
2,,,0
1
2,,,3,0
3,,,0
0,,,1
2,,,3,0
2
2,,,0
1
0
2,,,0
0
3,,,0
2,,,0
2,,,0
2,,,0,1
2
2
2
0
0
0
0
0
2,,,1
0,,,1
1
0,,,1
2,,,0
2,,,3,0
3,,,0
0
2,,,1
2,,,3
3,,,0
2,,,3,0
0
2
2
3,,,0
1
0
0,,,1
2,,,0
1
3
2,,,1
1
3
0
3,,,0,1
2,,,3,0,1
2,,,3,0
2,,,0,1
2,,,1
2,,,0
2,,,3,0
2,,,0,1
0
2
2
2,,,3,0
2
0
0
3,,,0
3,,,0,1
2,,,3,0
2,,,3,0,1
2
2
1
0,,,1
0
0
2
2,,,3,0,1
0
0,,,1
2,,,0,1
2
2
0,,,1
2
2
2,,,3,0
3
3,,,0,1
3,,,0
2,,,3,0
1
3,,,0
0,,,1
3
1
0
2
2
0
2,,,0,1
2
2,,,3,0
3
2,,,0
0
2
2
0
2
2,,,3,0
2,,,3,0
0,,,1
2
2,,,0
3,,,0,1
2,,,3,0
0,,,1
2,,,0,1
2,,,0
2,,,0
0
0
2,,,0,1
1
2,,,1
0
3,,,0,1
3,,,0,1
2
2,,,0,1
3,,,0
3,,,0
3
0,,,1
2
2,,,0
2,,,3
2,,,3,0
2,,,0
2,,,3,1
0
0,,,1
2,,,0,1
2,,,0
2
2,,,3
2,,,0
2,,,3,0
2
0
0
2,,,0,1
2
3,,,0
2,,,0
3
2
2
0
2,,,3,0
0,,,1
2,,,3,0
3
0
2
2,,,0,1
1
0
3
2,,,3
2,,,0
2,,,0
0
2,,,0
3,,,0
2,,,3,0
0
2
0
0
2,,,1
2,,,3,0,1
0
2,,,0
3
0
2
2,,,3,0,1
2,,,0,1
0
3,,,0,1
0
2,,,3,0,1
2
2,,,3,0
0
2
1
3,,,0
0
2,,,3,0,1
0
3
3,,,0
0
3
2
0
2
2
0
2,,,3,0,1
2,,,0
3
0
3,,,0
2,,,0
2,,,0
2
2,,,0,1
0
3
0
2,,,3,0
0
2,,,3,0
2
3
0
3,,,0
2,,,3,1,0
2
3,,,0
2
2
0
0
2,,,1
2
2,,,3,0,1
3
0,,,1
0
0
2
0
2,,,0
3,,,0
0
0
2
2,,,0,1
2
3,,,1,0
0
2,,,3
2
2,,,3
1
2,,,3,0
2
0
2
3
0
0,,,1
0,,,1
0
3
0
2,,,0
0
0
3,,,0
3,,,0
2
1
3
2,,,3,0,1
0,,,1
0
3
2
2,,,3,0
0
3
0
0,,,1
3
0,,,1
2
2,,,0,1
2,,,0
2,,,1
3,,,0
2
3
3
2
0
0
0
2
2,,,1
2,,,3,0
2,,,0,1
2
0
1
0
0,,,1
2
2
0
3,,,0
0
2,,,0
2
2,,,3
0
2
2,,,1
2,,,0
2,,,0,1
2,,,0,1
3,,,0
1
0
2,,,0
3,,,0,1
2
2,,,0
3,,,0
2
2,,,0,1
0
0
0
2,,,3,0
2,,,3,0
2,,,0
3
0
3,,,1
0
3
2
0
2
3
2
0
0
0
2
2,,,1
2,,,0
0
2,,,0
3,,,0
3,,,0,1
2,,,0
2,,,0,1
0
0
2
0
0
0
0
2
2
0
1
2,,,0
2
2,,,3,0
2
2,,,3,0
3
2,,,0
2
3
3,,,1
0
1
2
3,,,0,1
3
0
2
0
0
0
0
0
2
0
2
0,,,1
2,,,1
2,,,3,0
0
2,,,3,1,0
3
2
2,,,3,0
2,,,3,1
2,,,0
3
2,,,0
2,,,3,1
2,,,0
2,,,3,0,1
0
3
3
2,,,0
0
2
0
0,,,1
1
3
0
2
3,,,1
0
2
3,,,0
0
2,,,3,0,1
2,,,0
0
2,,,3,0,1
0
0
2
0
0,,,1
2,,,3
0,,,1
3
2
3,,,0
3,,,1
2
2
3,,,0
2,,,3,0,1
0
2
2
1
2
2
2,,,0
2,,,3,0
2,,,0
2,,,3,0
1
1
0
2,,,3,0,1
2,,,3,0,1
2,,,0
0
1
1
2,,,1
2,,,0
0
3,,,1
0
2,,,0
0
0
2
2,,,0
0,,,1
0
0
3,,,0
0
3,,,0
0
0
2,,,1
0
2,,,0,1
3,,,1
1
3,,,0
3,,,0
0
0
2,,,3
2,,,0
2
0
2,,,0
0
2
0,,,1
2,,,0
2,,,3
2
3
2
0
0,,,1
2
2
0
0
2
2
0
2
2
2
0
0
2,,,0
0
1
3
0
2
2,,,3,0
2,,,0,1
2
2,,,3,1
2
2,,,0,1
0
0
2
3
2,,,3,0,1
2
2,,,0
2
3
2,,,0
3
1
2,,,3
2
3,,,0
1
0
3,,,0,1
0
0
2,,,0
0
2,,,0
2,,,0
0,,,1
2
2,,,0
0
0
0
2,,,3,0
0
0
2
2
0
2,,,0
0
2,,,0
0
0
2
0
0
2,,,0
0
3
0,,,1
2,,,0
0
2,,,0,1
2,,,0
2,,,0
2
2,,,0
3
0
2,,,0
2
0
2
0
3
2
2
0
0
2,,,3,0
0
0
2,,,1
0
0
2
2
0
0
2,,,3,0
2
2,,,0,1
2
2,,,0
0
0
0
2,,,0
0
3,,,0,1
0
1
0
0
2,,,0
0
2,,,0
2
0,,,1
3,,,0,1
0
0
2,,,0
0
3,,,0
0
3
0
2
2,,,0
0
0
2,,,0
2
2,,,0
1
2,,,0
2,,,3,0
2,,,0
2,,,0
2
2,,,0
1
2,,,0
2,,,3,0
0,,,1
0
0
0
0
0
2,,,3
2,,,0
0
3,,,0
2,,,0
2,,,0
3,,,0
0
3
0
0
0
3
2,,,1
0
2
3
3
0
0
3,,,0
0
2,,,0,1
3
3
2,,,3,0,1
2
3
0
3
0
0
2
0
3
3,,,0
2
0
3,,,0
2,,,0
0
0
0
2,,,0
0
2
3,,,0
3
2
0
0
0
2
0
2
0
0
2
0
0
2
2
0
2,,,3,0
0
0
0
2
0
0
2,,,3,0
0
3,,,0
2
2,,,3,0
0
2
2,,,0
2,,,0
0
2
0
0
2,,,0
0
2
0
3
2
0
3,,,0
0
2
2,,,0
0
3
2,,,0
0
2,,,0
0
0
0
3
0
0
1
0
3
2,,,0
0,,,1
2,,,0
2
2
2,,,3
3,,,0
0
2
0
0
2
2
2,,,0
3,,,0
2
0
2,,,3
3
0
3
2,,,3
2,,,3,0
3
0
0,,,1
0
2,,,0
2
2,,,0
0
2,,,0
0
3
2
0
2,,,0
0
2
0
0
2
2,,,0
3,,,0
0
3
0
2,,,3
2
2
2,,,0
3
2,,,0
0
2
3,,,0
2
2,,,0,1
2
0
2
2
0
0
0
0
2,,,0
0,,,1
1
0
0
0
0
2
2,,,0
2,,,3,0
2,,,3
0
0
0
3,,,0
0
2,,,0
2,,,0,1,3
0
2,,,3,0
0
1
2,,,0,1
2,,,3,0
0
2,,,0
2,,,0
2,,,0
3,,,0
3
1
3
3,,,0
2
2,,,3,0,1
0
0
2,,,1
2,,,0
2,,,0
2,,,1
2
0
0
2
1
1
2,,,3,0
2,,,0
0
0
2,,,0
3,,,0
3
3
0
2,,,3
0,,,1
2,,,3,1
2,,,3,0
2,,,3,1
3,,,0
2
0
0
0
2,,,3,0
2,,,0
2,,,0
0
0,,,1
3,,,0
2
3
0
0
0
3
2,,,0
0
2
2,,,0
0
3,,,1
1
0
2,,,3
3
2,,,0
0
0
0
3,,,0
2,,,0
2
2,,,0
0
0
2
2,,,3,0
3,,,0
3,,,0
0
0
0
0
0
0,,,1
2,,,3,0
2
0
2,,,0
3
0
0
2,,,3
0
3,,,0
1
2,,,0
0,,,1
2
3
0
3
0
2,,,0
0
2,,,0
2,,,3,0,1
2,,,0
2,,,0
2,,,0
2
3,,,0
2,,,0
0
2
0
2
0
2,,,0
0
0
2,,,0
0
0
0
2,,,0
0
2
2,,,3
0
2,,,3,0
0
1
2,,,3,0
3,,,0
1
1
2,,,3,0,1
2
0
2
0,,,1
2,,,0
3,,,0
2,,,0
1
0
0
0
0
2
0
2,,,0
0
2,,,3,0
2,,,0
0
3
2
0
2
2
0
2,,,0
2,,,0
0
0
2,,,3,0
2,,,0
3,,,0
0
2,,,3,0,1
2
0
0
2,,,3
2,,,3,0
0
0
0
2,,,0
0
0
2
2,,,0
0
0
3,,,0
0
2,,,3
2,,,0
2,,,0
0
0
0
2,,,3,0
0
3,,,0
0
0
2,,,0
2,,,0
0,,,1
2
3,,,0
3
3,,,0
0
0
2,,,3,0
0
2,,,0
0
3
2,,,0
2
0
0
2
0
0
2,,,0
2,,,0
0
3
2
0
2
0
2,,,0
0
2,,,3,0
2,,,0,1
2
2,,,0
2
0
0
2,,,0,1
0
0
0
0
0
2,,,0
2,,,0
2,,,3,0,1
0
2,,,0
2,,,0
2
0
3,,,0
2
2
0
2,,,3,0
0
2,,,0
0
0
2
0
0
0
0
2,,,0
0
3,,,0
2
2
2,,,0
0
2,,,3,0
0
2
2,,,0
3,,,1
0
3,,,0
2,,,0
2
2
2
2
0
3,,,0
0
0
0
2,,,0
2,,,0
2
0
2,,,3,0
0
3
0,,,1,3
2,,,0
0
0,,,1
3,,,0
1
2,,,0
3,,,0
2
0
0
0
3,,,0
3,,,0
2,,,3,0
2
0
0
2,,,0
3
0
0
2,,,0
2,,,0
0
0,,,1
2,,,0
0
3
0
2,,,0,1
2,,,0
0
0
0
2,,,0
0,,,1
0
0
0
3,,,0
3
0
2,,,0
3,,,0
2
2,,,3
0,,,1
0
0
0
0
2,,,0
2,,,1
2,,,1
2
0
2
0
0
0
2
2,,,0
2
0
3,,,0
0
2
2,,,1
1
2,,,3,0
0,,,1
0
0
3,,,0
3,,,0
3,,,0
1
2,,,0
0
0
0
2
2,,,0,1
3,,,1
2
2
0
2,,,0
3,,,0
2,,,1
3,,,0
2
0
2,,,3,0,1
0
0
0
2,,,0
3,,,0
0,,,1
0
0
3,,,0
2,,,3,0
1
0,,,1
2
2,,,3
2
2,,,3,0
2
3,,,1,0
2
2,,,0
2,,,0
2,,,0
2
3,,,1
2
2
2
2,,,3,0
1
2
0
2,,,3,0
2
3
3,,,0
0,,,1
0
2,,,0
2,,,0
3,,,0
2,,,3,0
2
1
2,,,0
3,,,1
3,,,0
2
0
0
2,,,0
3,,,0
2,,,1
0
2
2,,,3
0
2,,,1
0
3,,,0
3
1
2
2
2
2,,,0
0
0
1
2,,,0
2
3,,,0
0
0
2,,,0
0
3,,,0
0
2,,,3,0,1
2
0,,,1
2,,,0,1
0
0
3
2,,,0
0
2
2,,,0
2,,,0
3,,,0
2,,,0
0
0
2
0,,,1
2
2,,,0
0
0
2
0
3,,,1
2
0
2,,,0
0
0
2,,,0
2,,,3,0
2
3
3,,,0
3,,,0
0
2,,,3,0
0
2,,,3,0
3,,,0
2
1
2
2,,,0,1
2,,,0
2,,,3
0,,,1
1
2
3,,,0
0
3,,,0
0
2,,,0
3,,,0
0,,,1
0
0
3
2
3,,,0
0
2
2,,,0
0
2
2,,,0
3,,,0,1
2
2,,,0,1
3,,,0
2,,,0
2,,,3
2
2,,,0
2,,,1,0
2
0
0
2
2,,,3
2,,,3,0
3,,,0
3,,,0
3,,,0
2
0
0
2,,,0
2,,,3
2,,,0
2,,,3
0
0,,,1
3
2
2
0
2,,,0
0
0,,,1
0
2,,,0
2,,,3,0
3
0
2,,,0
3,,,1
0
2,,,3
0
2
3
3,,,0
2,,,0
0
0
2,,,0
2,,,0
2,,,3,0,1
2,,,3
0
0
2,,,0
2,,,1
2
2,,,3,0
2
2,,,3,0
2
3
2
2
0
0
2
0
2
1
2
2,,,0
0
0
3,,,1
2
2,,,3,0,1
3
2,,,3,0
3,,,1
2,,,3,0
3,,,0
0
2,,,0
2
0
0
1
2,,,0
2
0
0
2,,,3,0
0
2,,,3,0
0
0
2,,,3,0
1
3,,,0
0
2,,,0
3,,,0
3,,,0
2,,,3,0
0
2
2,,,1,0
2,,,0
2,,,0
2,,,3,0
0
0
2
0
3,,,0
2,,,0
0
1
2,,,0
0
2
0
2,,,3,0
2,,,3
2,,,3,0
2,,,1
0
0
2,,,3,0
0
2
1
0
0
0
3
2,,,3,0,1
2,,,0
2,,,3,0,1
2,,,3
3
0
2,,,3,0,1
2,,,3,0
3,,,0,1
0
2
2,,,0
3
2,,,3,0
0
2,,,3,0
2
2,,,0
1
0,,,1
3,,,0
2
3,,,0,1
2
2,,,3,0
3
1
1
2
2,,,3,0
2,,,0,1
0
2,,,3,0
0,,,1
2
3
2,,,0,1
2,,,0
2,,,0
0
2
2
2,,,3,0
2
0
0
0
3
0
0,,,1
2,,,3,0
3
0
3
3
0
2
0
0
0
0
1
2
0
0
2
3
0
0,,,1
2
0
2
0
0
0
2
2,,,0
0
0
0
2,,,0,1
3
0
1
0
2,,,0
3
2
1
2
2
0
2
0
0
3,,,0
3,,,0
1
3
0
3,,,0
2,,,0
2
3
0
3,,,0
2
0
1
0,,,1
3,,,1
2
0
2,,,0
0
3,,,0,1
2,,,3,0,1
2,,,0,1
2,,,0
2,,,3
0
0
0
2,,,0
3
2
2
2,,,3,0,1
2,,,3
0
2
0
2
0,,,1
2
0,,,1
2
2
0,,,1
2,,,0
0
2,,,1
1
0
0,,,1
2,,,0
0,,,1
2,,,3,1
1
0
0
2,,,0
2,,,0,1,3
2
2
2,,,0,1
3
3
3,,,0,1
2
0
3,,,0
0
0
3,,,0
0
0
2,,,0
3,,,1
3,,,0,1
1
0
2
0
2,,,0
2,,,3
3,,,0
2
2,,,0
2,,,0,1
0
3
3,,,0
3,,,0,1
2
2
2
2
2,,,0
2,,,3,0,1
0
2,,,3,0,1
2,,,1
2
2
2
2,,,3,0
0,,,1
2
3
3
3,,,1
2
2
0,,,1
0
2
2
2,,,0,1
3
1
0
3,,,0
2,,,0,1
2
0
0
2,,,3,0
0
0
3
0
2,,,3,0
2,,,0
2,,,3,0,1
0
2,,,3,0
3
1
2,,,0
3,,,0
0
3
2
0
3
2
0
0
2
2
2
2,,,1
3
3
1
0
2
3
2
3
1
2
2,,,0,1
2,,,0
0
2
2,,,1
3
3,,,0
3,,,0
3
1
3,,,0
3
3
2,,,3,1
2
3
3
2,,,0
1
0,,,1
2
0,,,1
2
2,,,0
3
2,,,0
0,,,1
3
1

In [77]:
cj_grp

,gender,age_grp,weekday,total_qty,total_amt,category,event_product,num_category,amt/qty,employee_yn
scd,,,,,,,,,,
20230101963221,0,3,0,1,7.959975,1,0,1,7.959975,N
20230101963226,1,3,0,8,37.321156,"2,,,1",0,2,4.665145,Y
20230101963229,1,5,0,1,9.003808,2,0,1,9.003808,Y
20230101963246,1,2,0,2,9.574080,1,0,1,4.787040,Y
20230101963265,0,3,0,5,43.665790,"2,,,0,1",0,3,8.733158,Y
...,...,...,...,...,...,...,...,...,...,...
20230131216228,0,3,1,2,9.021961,3,0,1,4.510980,N
20230131216338,1,4,1,3,16.394430,"2,,,0",0,2,6.092155,N
20230131216371,0,3,1,2,16.019650,"0,,,1",0,2,8.009825,N
20230131216446,0,4,1,1,8.655214,3,0,1,8.655214,N
20230131216584,1,4,1,1,9.036701,1,0,1,9.036701,N

In [78]:
cj_grp['ctg_0']=0
cj_grp['ctg_1']=0
cj_grp['ctg_2']=0
cj_grp['ctg_3']=0

In [79]:
ctg = ['0', '1', '2', '3']

for i in range(len(cj_grp)):
    for j in ctg:
        if j in cj_grp['category'].iloc[i]:
            col = 'ctg_' + j
            cj_grp[col].iloc[i] = 1

<ipython-input-79-1a090e4e5303>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cj_grp[col].iloc[i] = 1

In [80]:
cj_grp

,gender,age_grp,weekday,total_qty,total_amt,category,event_product,num_category,amt/qty,employee_yn,ctg_0,ctg_1,ctg_2,ctg_3
scd,,,,,,,,,,,,,,
20230101963221,0,3,0,1,7.959975,1,0,1,7.959975,N,0,1,0,0
20230101963226,1,3,0,8,37.321156,"2,,,1",0,2,4.665145,Y,0,1,1,0
20230101963229,1,5,0,1,9.003808,2,0,1,9.003808,Y,0,0,1,0
20230101963246,1,2,0,2,9.574080,1,0,1,4.787040,Y,0,1,0,0
20230101963265,0,3,0,5,43.665790,"2,,,0,1",0,3,8.733158,Y,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230131216228,0,3,1,2,9.021961,3,0,1,4.510980,N,0,0,0,1
20230131216338,1,4,1,3,16.394430,"2,,,0",0,2,6.092155,N,1,0,1,0
20230131216371,0,3,1,2,16.019650,"0,,,1",0,2,8.009825,N,1,1,0,0
20230131216446,0,4,1,1,8.655214,3,0,1,8.655214,N,0,0,0,1
20230131216584,1,4,1,1,9.036701,1,0,1,9.036701,N,0,1,0,0

In [81]:
cj_grp.drop(['category'], axis = 1, inplace=True)
cj_grp

,gender,age_grp,weekday,total_qty,total_amt,event_product,num_category,amt/qty,employee_yn,ctg_0,ctg_1,ctg_2,ctg_3
scd,,,,,,,,,,,,,
20230101963221,0,3,0,1,7.959975,0,1,7.959975,N,0,1,0,0
20230101963226,1,3,0,8,37.321156,0,2,4.665145,Y,0,1,1,0
20230101963229,1,5,0,1,9.003808,0,1,9.003808,Y,0,0,1,0
20230101963246,1,2,0,2,9.574080,0,1,4.787040,Y,0,1,0,0
20230101963265,0,3,0,5,43.665790,0,3,8.733158,Y,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230131216228,0,3,1,2,9.021961,0,1,4.510980,N,0,0,0,1
20230131216338,1,4,1,3,16.394430,0,2,6.092155,N,1,0,1,0
20230131216371,0,3,1,2,16.019650,0,2,8.009825,N,1,1,0,0
20230131216446,0,4,1,1,8.655214,0,1,8.655214,N,0,0,0,1
20230131216584,1,4,1,1,9.036701,0,1,9.036701,N,0,1,0,0

In [82]:
# 임직원 데이터
cj_y = cj_grp[cj_grp['employee_yn']=='Y']
cj_y = cj_y.drop(['employee_yn'], axis = 1)

In [84]:
cj_y = cj_y[['gender', 'age_grp', 'weekday', 'total_qty', 'total_amt', 'event_product', 'amt/qty', 'num_category', 'ctg_0', 'ctg_1', 'ctg_2', 'ctg_3']]
cj_y.to_csv('cj_empY.csv')

In [85]:
# 비임직원 데이터
cj_n = cj_grp[cj_grp['employee_yn']=='N']
cj_n = cj_n.drop(['employee_yn'], axis = 1)

In [86]:
cj_n = cj_n[['gender', 'age_grp', 'weekday', 'total_qty', 'total_amt', 'event_product', 'amt/qty', 'num_category', 'ctg_0', 'ctg_1', 'ctg_2', 'ctg_3']]
cj_n.to_csv('cj_empN.csv')